const AVATAR_API='https://motor-invencoes.edsonfernandesvet.workers.dev';
const STORE='futuro_avatar_draft_v2';
const $=id=>document.getElementById(id);
const defaults={version:2,body:{height:.52,width:.48,shoulders:.5,muscle:.38,leg:.52,arm:.48},face:{head:.5,jaw:.5,eyes:.5,nose:.5,mouth:.5,brow:.5},hair:{style:'curto',color:'#171717'},style:{skin:'#c58b68',eye:'#171717'},clothes:{top:'tech',color:'#26354d'},accessory:'none'};
let state={sex:null,config:structuredClone(defaults)};
function token(){return localStorage.getItem('futuro_auth_token')||''}
function merge(base,src){for(const k in base){if(src?.[k]&&typeof base[k]==='object'&&!Array.isArray(base[k]))merge(base[k],src[k]);else if(src?.[k]!==undefined)base[k]=src[k]}return base}
function draft(){try{localStorage.setItem(STORE,JSON.stringify(state))}catch{}}
function loadDraft(){try{const x=JSON.parse(localStorage.getItem(STORE)||'null');if(x?.sex)state={sex:x.sex,config:merge(structuredClone(defaults),x.config||{})}}catch{}}
function status(x){$('status').textContent=x||''}
function ensureExtraControls(){if(document.getElementById('avatarExtras'))return;const box=document.createElement('div');box.id='avatarExtras';box.className='group';box.innerHTML=`<h3>ESTILO E IDENTIDADE</h3><label style="font-size:11px;font-weight:800;display:block;margin-bottom:8px">Roupa<select id="topStyle"><option value="tech">Traje Tech</option><option value="jaqueta">Jaqueta Futurista</option><option value="armadura">Armadura Absurda</option><option value="casual">Casual</option><option value="macacao">Macacão</option></select></label><label style="font-size:11px;font-weight:800;display:block;margin:10px 0">Cor da roupa<input id="topColor" type="color" value="#26354d"></label><label style="font-size:11px;font-weight:800;display:block">Acessório<select id="accessory"><option value="none">Nenhum</option><option value="visor">Visor holográfico</option><option value="goggles">Óculos tecnológicos</option><option value="ear">Comunicador auricular</option><option value="antenna">Antena neural</option></select></label>`;document.querySelector('.controls').appendChild(box);$('topStyle').onchange=e=>{state.config.clothes.top=e.target.value;draft();render()};$('topColor').oninput=e=>{state.config.clothes.color=e.target.value;draft();render()};$('accessory').onchange=e=>{state.config.accessory=e.target.value;draft();render()}}
function esc(s){return String(s).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function svg(){const c=state.config,b=c.body,f=c.face,h=c.hair,cl=c.clothes,skin=c.style.skin||'#c58b68',eye=c.style.eye||'#171717',female=state.sex==='feminino';const cx=210;
 const height=0.88+b.height*.22, torsoW=(female?132:150)*(0.88+b.width*.24), shoulder=(female?126:156)*(0.82+b.shoulders*.32), headW=(female?100:108)*(0.9+f.head*.2), headH=118*(0.91+f.head*.18), neck=34, top=192, hip=352*height, footY=505*height, legW=(female?38:43)*(0.86+b.leg*.25), armW=(female?28:34)*(0.86+b.arm*.28);const jaw=1+f.jaw*.12, eyeGap=18+f.eyes*10, eyeSize=5+f.eyes*3, mouthW=20+f.mouth*25, brow=2+f.brow*3;
 let hair='';if(h.style==='moicano')hair=`<path d="M${cx-headW*.44} 73 C185 58 188 34 199 45 L210 18 L221 45 C232 34 235 58 ${cx+headW*.44} 73 L${cx+headW*.34} 91 L${cx-headW*.34} 91Z" fill="${h.color}"/>`;else if(h.style==='longo')hair=`<path d="M${cx-headW*.5} 92 C${cx-headW*.63} 22 ${cx+headW*.55} 18 ${cx+headW*.5} 92 L${cx+headW*.64} 202 Q${cx+headW*.39} 180 ${cx+headW*.3} 116 L${cx-headW*.3} 116 Q${cx-headW*.4} 180 ${cx-headW*.64} 202Z" fill="${h.color}"/>`;else if(h.style==='futuro')hair=`<path d="M${cx-headW*.5} 92 Q${cx-headW*.53} 29 ${cx} 24 Q${cx+headW*.53} 29 ${cx+headW*.5} 92 L${cx+headW*.38} 73 Q${cx} 48 ${cx-headW*.38} 73Z" fill="${h.color}"/><path d="M${cx-headW*.34} 53 Q${cx} 35 ${cx+headW*.34} 53" fill="none" stroke="#8de8ff" stroke-width="5"/>`;else if(h.style!=='careca')hair=`<path d="M${cx-headW*.5} 92 Q${cx-headW*.54} 27 ${cx} 24 Q${cx+headW*.54} 27 ${cx+headW*.5} 92 Q${cx+headW*.38} 70 ${cx} 68 Q${cx-headW*.38} 70 ${cx-headW*.5} 92Z" fill="${h.color}"/>`;
 const bodyTop=top, bodyBottom=hip;let clothing='';if(cl.top==='armadura')clothing=`<path d="M${cx-shoulder/2} ${bodyTop+2} L${cx-torsoW*.5} 255 Q${cx-torsoW*.42} ${bodyBottom-22} ${cx-torsoW*.28} ${bodyBottom} L${cx+torsoW*.28} ${bodyBottom} Q${cx+torsoW*.42} ${bodyBottom-22} ${cx+torsoW*.5} 255 L${cx+shoulder/2} ${bodyTop+2}Z" fill="${cl.color}" stroke="#8de8ff" stroke-width="4"/><path d="M${cx-shoulder*.34} 220L${cx} 250L${cx+shoulder*.34} 220" fill="none" stroke="#d8ff55" stroke-width="5"/>`;else if(cl.top==='jaqueta')clothing=`<path d="M${cx-shoulder/2} ${bodyTop+2} L${cx-torsoW*.5} 255 Q${cx-torsoW*.42} ${bodyBottom-22} ${cx-torsoW*.28} ${bodyBottom} L${cx+torsoW*.28} ${bodyBottom} Q${cx+torsoW*.42} ${bodyBottom-22} ${cx+torsoW*.5} 255 L${cx+shoulder/2} ${bodyTop+2}Z" fill="${cl.color}" stroke="#111827" stroke-width="3"/><path d="M${cx} 205V${bodyBottom-4}" stroke="#8de8ff" stroke-width="3"/>`;else if(cl.top==='casual')clothing=`<path d="M${cx-shoulder/2} ${bodyTop+3} L${cx-torsoW*.5} 255 Q${cx-torsoW*.42} ${bodyBottom-22} ${cx-torsoW*.28} ${bodyBottom} L${cx+torsoW*.28} ${bodyBottom} Q${cx+torsoW*.42} ${bodyBottom-22} ${cx+torsoW*.5} 255 L${cx+shoulder/2} ${bodyTop+3}Z" fill="${cl.color}"/>`;else clothing=`<path d="M${cx-shoulder/2} ${bodyTop+3} L${cx-torsoW*.5} 255 Q${cx-torsoW*.42} ${bodyBottom-22} ${cx-torsoW*.28} ${bodyBottom} L${cx+torsoW*.28} ${bodyBottom} Q${cx+torsoW*.42} ${bodyBottom-22} ${cx+torsoW*.5} 255 L${cx+shoulder/2} ${bodyTop+3}Z" fill="${cl.color}" stroke="#8de8ff" stroke-width="2"/>`;
 let acc='';if(state.config.accessory==='visor')acc=`<path d="M${cx-headW*.48} 77 Q${cx} 55 ${cx+headW*.48} 77 L${cx+headW*.4} 96 Q${cx} 107 ${cx-headW*.4} 96Z" fill="#15283b" stroke="#8de8ff" stroke-width="3" opacity=".95"/>`;if(state.config.accessory==='goggles')acc=`<rect x="${cx-eyeGap-eyeSize-7}" y="70" width="${eyeSize*2+14}" height="18" rx="8" fill="#15283b" stroke="#8de8ff" stroke-width="2"/><rect x="${cx+eyeGap-7}" y="70" width="${eyeSize*2+14}" height="18" rx="8" fill="#15283b" stroke="#8de8ff" stroke-width="2"/>`;if(state.config.accessory==='ear')acc=`<circle cx="${cx-headW*.52}" cy="101" r="9" fill="#8de8ff"/><circle cx="${cx+headW*.52}" cy="101" r="9" fill="#8de8ff"/>`;if(state.config.accessory==='antenna')acc=`<path d="M${cx+headW*.34} 42Q${cx+headW*.52} 18 ${cx+headW*.62} 12" fill="none" stroke="#8de8ff" stroke-width="4"/><circle cx="${cx+headW*.62}" cy="12" r="6" fill="#d8ff55"/>`;
 return `<svg class="avatar-svg" viewBox="0 0 420 540" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="bg" x1="0" x2="1" y1="0" y2="1"><stop stop-color="#07111f"/><stop offset="1" stop-color="#162b45"/></linearGradient><radialGradient id="skin" cx="35%" cy="25%"><stop stop-color="#f1c3a2"/><stop offset=".7" stop-color="${skin}"/><stop offset="1" stop-color="#704737"/></radialGradient><filter id="glow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><rect width="420" height="540" rx="18" fill="url(#bg)"/><g opacity=".18" stroke="#8de8ff"><path d="M20 100H400M20 180H400M20 260H400M20 340H400M20 420H400"/><path d="M70 20V480M140 20V480M210 20V480M280 20V480M350 20V480"/></g><text x="25" y="30" fill="#9eb1d0" font-size="9" font-weight="900" letter-spacing="2">FUTUROLOGIO // AVATAR LAB</text><ellipse cx="210" cy="492" rx="126" ry="20" fill="#8de8ff" opacity=".12"/><path d="M75 493H345" stroke="#8de8ff" opacity=".55"/>
 <g stroke="#111827" stroke-width="3"><rect x="${cx-shoulder/2-armW/2}" y="205" width="${armW}" height="${bodyBottom-bodyTop-4}" rx="${armW/2}" fill="url(#skin)"/><rect x="${cx+shoulder/2-armW/2}" y="205" width="${armW}" height="${bodyBottom-bodyTop-4}" rx="${armW/2}" fill="url(#skin)"/><path d="M${cx-shoulder/2} ${bodyTop} Q${cx-torsoW*.52} 250 ${cx-torsoW*.3} ${bodyBottom} L${cx+torsoW*.3} ${bodyBottom} Q${cx+torsoW*.52} 250 ${cx+shoulder/2} ${bodyTop}Z" fill="url(#skin)"/>${clothing}<rect x="${cx-14}" y="166" width="28" height="44" rx="12" fill="url(#skin)"/><rect x="${cx-torsoW*.22}" y="${bodyBottom-3}" width="${legW}" height="${footY-bodyBottom}" rx="${legW/2}" fill="url(#skin)"/><rect x="${cx+torsoW*.22-legW}" y="${bodyBottom-3}" width="${legW}" height="${footY-bodyBottom}" rx="${legW/2}" fill="url(#skin)"/></g>
 <ellipse cx="${cx}" cy="82" rx="${headW/2}" ry="${headH/2}" fill="url(#skin)" stroke="#111827" stroke-width="3" transform="rotate(${(f.jaw-.5)*4} ${cx} 82)"/>${hair}<path d="M${cx-eyeGap-7} ${67-f.brow*2}L${cx-eyeGap+7} ${64-f.brow*2}" stroke="#5b372c" stroke-width="${brow}" stroke-linecap="round"/><path d="M${cx+eyeGap-7} ${64-f.brow*2}L${cx+eyeGap+7} ${67-f.brow*2}" stroke="#5b372c" stroke-width="${brow}" stroke-linecap="round"/><ellipse cx="${cx-eyeGap}" cy="78" rx="${eyeSize}" ry="${eyeSize*.72}" fill="#f7f7f2" stroke="#5b372c"/><ellipse cx="${cx+eyeGap}" cy="78" rx="${eyeSize}" ry="${eyeSize*.72}" fill="#f7f7f2" stroke="#5b372c"/><circle cx="${cx-eyeGap}" cy="79" r="${Math.max(2,eyeSize*.42)}" fill="${eye}"/><circle cx="${cx+eyeGap}" cy="79" r="${Math.max(2,eyeSize*.42)}" fill="${eye}"/><path d="M${cx-3} 82Q${cx+4+f.nose*5} 98 ${cx-1} 105Q${cx-7} 108 ${cx-2} 109" fill="none" stroke="#8d5f49" stroke-width="3" stroke-linecap="round"/><path d="M${cx-mouthW/2} 126 Q${cx} ${126+f.mouth*9} ${cx+mouthW/2} 126" fill="none" stroke="#6b3d35" stroke-width="4" stroke-linecap="round"/><path d="M${cx-mouthW*.3} 132 Q${cx} ${134+f.mouth*4} ${cx+mouthW*.3} 132" fill="none" stroke="#f2b5a0" stroke-width="2"/>${acc}<g filter="url(#glow)"><circle cx="${cx}" cy="242" r="7" fill="#d8ff55"/><circle cx="${cx}" cy="242" r="14" fill="none" stroke="#d8ff55" opacity=".25"/></g><text x="210" y="522" text-anchor="middle" fill="#9eb1d0" font-size="8" font-weight="900" letter-spacing="1.4">PERSONAGEM // ${state.sex.toUpperCase()} // V2</text></svg>`}
function render(){if(!state.sex)return;ensureExtraControls();$('preview').innerHTML=svg();document.querySelectorAll('input[type=range][data-group]').forEach(e=>{e.value=state.config[e.dataset.group][e.dataset.key];e.nextElementSibling.value=Math.round(e.value*100)+'%'});$('hairStyle').value=state.config.hair.style;$('hairColor').value=state.config.hair.color;$('skinColor').value=state.config.style.skin;$('topStyle').value=state.config.clothes.top;$('topColor').value=state.config.clothes.color;$('accessory').value=state.config.accessory}
function choose(sex){state.sex=sex;draft();$('sexStep').classList.add('hidden');$('editStep').classList.remove('hidden');$('sexBadge').textContent='ETAPA 02 // '+sex.toUpperCase();render();status('')}
document.querySelectorAll('.sex-card').forEach(b=>b.onclick=()=>choose(b.dataset.sex));
document.querySelectorAll('input[type=range][data-group]').forEach(e=>e.oninput=()=>{state.config[e.dataset.group][e.dataset.key]=Math.max(0,Math.min(1,Number(e.value)));draft();render()});
$('hairStyle').onchange=e=>{state.config.hair.style=e.target.value;draft();render()};$('hairColor').oninput=e=>{state.config.hair.color=e.target.value;draft();render()};$('skinColor').oninput=e=>{state.config.style.skin=e.target.value;draft();render()};
$('changeSex').onclick=()=>{$('editStep').classList.add('hidden');$('sexStep').classList.remove('hidden')};
$('resetBtn').onclick=()=>{if(!confirm('Recomeçar o avatar?'))return;state={sex:null,config:structuredClone(defaults)};localStorage.removeItem(STORE);$('editStep').classList.add('hidden');$('sexStep').classList.remove('hidden')};
$('saveBtn').onclick=async()=>{draft();const t=token();if(!t){status('Avatar salvo neste dispositivo. Entre na sua conta para sincronizá-lo com o FUTUROLOGIO.');return}status('Salvando avatar…');try{const r=await fetch(AVATAR_API+'/api/avatar',{method:'PUT',headers:{'content-type':'application/json',authorization:'Bearer '+t},body:JSON.stringify(state)});const d=await r.json();if(!r.ok)throw Error(d.error||'Falha');state.config=merge(structuredClone(defaults),d.avatar.config);draft();status('Avatar salvo no seu perfil.')}catch{status('Falha na sincronização. O avatar continua salvo neste dispositivo.')}};
async function remote(){const t=token();if(!t)return;try{const r=await fetch(AVATAR_API+'/api/avatar',{headers:{authorization:'Bearer '+t}}),d=await r.json();if(d.avatar?.sex){state={sex:d.avatar.sex,config:merge(structuredClone(defaults),d.avatar.config||{})};draft();choose(state.sex)}}catch{}}
loadDraft();if(state.sex)choose(state.sex);remote();