(()=>{'use strict';
const REQUIRED=['what','realTech','specTech','inventedTech','build','uses','dangers','curiosity','tests'];
const MIN={what:160,realTech:45,specTech:45,inventedTech:45,build:45,uses:30,dangers:40,curiosity:70,tests:70};
const CAT={'CASA & VIDA DOMÉSTICA':'Casa','TRABALHO & ESCRITÓRIO':'Escola & Trabalho','TRANSPORTE & TRÂNSITO':'Transporte','RELACIONAMENTOS & FAMÍLIA':'Mente & Comportamento','TECNOLOGIA & FUTURO':'Tecnologia do futuro','COMIDA & RESTAURANTES':'Comida & Cozinha','EDUCAÇÃO & FACULDADE':'Escola & Trabalho','DINHEIRO & CONSUMISMO':'Dinheiro & Negócios','SOCIEDADE & BUROCRACIA':'Cidade','ACADEMIA & ESPORTE':'Esportes','LAZER & ENTRETENIMENTO':'Entretenimento','VIZINHANÇA & CONVIVÊNCIA':'Cidade','ANIMAIS & PETS':'Animais','VIAGENS & TURISMO':'Viagem'};
const $=id=>document.getElementById(id);
const text=v=>Array.isArray(v)?v.map(text).join(' '):v&&typeof v==='object'?Object.values(v).map(text).join(' '):String(v??'').trim();
const norm=v=>text(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\w\s]/g,' ').replace(/\s+/g,' ').trim();
function unwrap(v){if(Array.isArray(v))return v;if(v&&Array.isArray(v.products))return v.products;if(v&&Array.isArray(v.produtos))return v.produtos;if(v&&typeof v==='object')return [v];throw Error('Formato JSON não reconhecido.');}
function clean(p,i){const q={...p};q.id=text(q.id)||`produto-${i}`;q.name=text(q.name||q.nome);q.category=CAT[text(q.category)]||text(q.category||q.categoria);return q;}
function validate(p){const e=[];if(!p.name)e.push('name ausente');if(!p.category)e.push('category ausente');for(const f of REQUIRED)if(text(p[f]).length<MIN[f])e.push(`${f} curto`);return e;}
let result=[];
function convert(){let incoming;try{incoming=unwrap(JSON.parse($('input').value.trim()));}catch(e){$('report').textContent='ERRO: '+e.message;return;}const base=Array.isArray(window.FUTUROLOGIO_PRODUCTS)?window.FUTUROLOGIO_PRODUCTS:[];const all=[...base,...incoming.map((p,i)=>clean(p,i+1))];const ids=new Set(),names=new Set(),whats=new Set(),errors=[],out=[];for(const p of all){const e=validate(p);if(e.length){errors.push(`${p.id||'?'}: ${e.join(', ')}`);continue;}const id=String(p.id),n=norm(p.name),w=norm(p.what);if(ids.has(id)||names.has(n)||whats.has(w))continue;ids.add(id);names.add(n);whats.add(w);out.push(p);}result=out;render(errors,incoming.length,base.length);}
function render(errors,inc,base){$('report').textContent=`Entrada: ${inc}\nBase: ${base}\nResultado: ${result.length}\nRejeitados: ${errors.length}\n\n${errors.slice(0,80).join('\n')||'Nenhum produto rejeitado.'}`;$('download').disabled=false;$('copy').disabled=false;}
function download(){const b=new Blob([JSON.stringify(result,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='catalog.json';a.click();}
$('convert').onclick=convert;$('download').onclick=download;$('copy').onclick=async()=>{await navigator.clipboard.writeText(JSON.stringify(result,null,2));$('report').textContent+='\n\nJSON copiado.';};
})();