(()=>{
'use strict';
if(window.__FUTUROLOGIO_CREATION_CORE)return;
window.__FUTUROLOGIO_CREATION_CORE=true;
const API='https://motor-invencoes.edsonfernandesvet.workers.dev';
const CATS=['Casa','Comida & Cozinha','Transporte','Moda','Animais','Tecnologia','Mente & Comportamento','Meio Ambiente','Escola & Trabalho','Espaço','Sem sentido','Tecnologia do futuro','Indústria','Esportes','Entretenimento','Dinheiro & Negócios','Cidade','Agricultura','Viagem','Comunicação','Energia','Tempo & Clima','Objetos pessoais','Lazer','Museu','Bizarro ou Nojento'];
let selected='Casa',used=[],impactAudioCtx=null;
try{used=JSON.parse(localStorage.getItem('futuro_used_v3')||'[]')}catch{}
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function sectionHTML(v,label){if(!v)return '<p>Não informado no lote.</p>';if(Array.isArray(v))return v.map(x=>'<div class="techItem"><span class="techLabel">'+esc(label)+'</span><b>'+esc(x.name||x.title||'Tecnologia')+'</b><p>'+esc(x.description||x.what||x.text||'')+'</p></div>').join('');return '<p>'+esc(v)+'</p>'}
function score(p){const t=(p.realTech||'').length,s=(p.specTech||'').length,i=(p.inventedTech||'').length;let a=Math.max(10,Math.min(70,Math.round(t/(t+s+i||1)*100))),b=Math.max(5,Math.min(50,Math.round(s/(t+s+i||1)*100))),c=100-a-b;if(c<10){c=10;a=Math.max(10,100-b-c)}return[a,b,c]}
function renderCats(){const el=$('cats');if(!el||el.dataset.coreReady)return;el.dataset.coreReady='1';el.innerHTML='';CATS.forEach(c=>{const b=document.createElement('button');b.className='cat'+(c===selected?' selected':'');b.textContent=c;b.onclick=()=>{selected=c;$('selectedCat').textContent=c;document.querySelectorAll('.cat').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')};el.appendChild(b)})}
function addHistory(p){if(!p?.id)return;used=used.filter(x=>x!==p.id);used.push(p.id);localStorage.setItem('futuro_used_v3',JSON.stringify(used));const h=$('history');if(!h)return;h.innerHTML='';used.slice(-12).reverse().forEach(id=>{const q=window.FUTUROLOGIO_PRODUCTS?.find(x=>x.id===id);if(q){const s=document.createElement('span');s.textContent=q.name;h.appendChild(s)}})}
function installImpactStyle(){if(document.getElementById('futuroImpactStyle'))return;const s=document.createElement('style');s.id='futuroImpactStyle';s.textContent='@keyframes futuroCreationShake{0%,100%{transform:translate3d(0,0,0)}12%{transform:translate3d(-8px,2px,0)}25%{transform:translate3d(7px,-2px,0)}38%{transform:translate3d(-6px,1px,0)}52%{transform:translate3d(5px,-1px,0)}66%{transform:translate3d(-3px,0,0)}82%{transform:translate3d(1px,0,0)}}.futuro-creation-shake{animation:futuroCreationShake .46s cubic-bezier(.36,.07,.19,.97) both}';document.head.appendChild(s)}
function creationImpact(){try{const AC=window.AudioContext||window.webkitAudioContext;if(AC){impactAudioCtx=impactAudioCtx||new AC();const ctx=impactAudioCtx;if(ctx.state==='suspended')ctx.resume();const now=ctx.currentTime,duration=.42,buffer=ctx.createBuffer(1,Math.floor(ctx.sampleRate*duration),ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++){const t=i/data.length;data[i]=(Math.random()*2-1)*(1-t)*(1-t)}const noise=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();noise.buffer=buffer;filter.type='lowpass';filter.frequency.setValueAtTime(1800,now);filter.frequency.exponentialRampToValueAtTime(180,now+duration);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.65,now+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);noise.connect(filter).connect(gain).connect(ctx.destination);noise.start(now);noise.stop(now+duration);const osc=ctx.createOscillator(),og=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(110,now);osc.frequency.exponentialRampToValueAtTime(38,now+.28);og.gain.setValueAtTime(.0001,now);og.gain.exponentialRampToValueAtTime(.45,now+.01);og.gain.exponentialRampToValueAtTime(.0001,now+.32);osc.connect(og).connect(ctx.destination);osc.start(now);osc.stop(now+.34)}}catch{}try{const target=document.body;target.classList.remove('futuro-creation-shake');void target.offsetWidth;target.classList.add('futuro-creation-shake');setTimeout(()=>target.classList.remove('futuro-creation-shake'),500)}catch{}}
function show(p,opts={}){if(!p)return;window.FUTUROLOGIO_CURRENT_PRODUCT=p;window.FUTUROLOGIO_CURRENT_DB_ID=Number(p.__dbId||0);$('result')?.classList.remove('hidden');['name','subtitle','readiness','year','patent','build','uses','danger','test','curiosity'].forEach(k=>{const el=$(k);if(el)el.textContent=p[k==='danger'?'dangers':k==='test'?'tests':k]||'Não informado no lote.'});if($('intro'))$('intro').textContent=p.what||'Não informado no lote.';if($('what'))$('what').textContent=p.what||'Não informado no lote.';if($('real'))$('real').innerHTML=sectionHTML(p.realTech,'Real');if($('spec'))$('spec').innerHTML=sectionHTML(p.specTech,'Especulativa');if($('imp'))$('imp').textContent=p.inventedTech||'Não informado no lote.';const q=score(p);['r','s','i'].forEach((id,n)=>{if($(id))$(id).style.width=q[n]+'%'});if($('reality'))$('reality').textContent=q[0]+'% baseado em tecnologia existente, '+q[1]+'% especulativo e '+q[2]+'% totalmente inventado.';if($('stamp'))$('stamp').textContent='Registro FUT-'+String(p.id||'').toUpperCase()+'-'+Date.now().toString(36).toUpperCase();if(!opts.public){addHistory(p);window.FUTUROLOGIO_AFTER_CREATE?.(p);creationImpact()}setTimeout(()=>window.scrollTo({top:($('result')?.offsetTop||0)-15,behavior:'smooth'}),20)}
window.show=show;
window.newInvention=async function(){const pool=(window.FUTUROLOGIO_PRODUCTS||[]).filter(p=>p.category===selected&&!used.includes(p.id));if(!pool.length){alert('Essa categoria já mostrou todos os produtos disponíveis. Escolha outra categoria.');return}show(pool[Math.floor(Math.random()*pool.length)])};
async function openDb(id){try{const d=await fetch(API+'/api/invention/'+encodeURIComponent(id)).then(r=>r.json());if(!d.ok)return false;const p=(window.FUTUROLOGIO_PRODUCTS||[]).find(x=>String(x.id)===String(d.source_id))||(window.FUTUROLOGIO_PRODUCTS||[]).find(x=>x.name===d.name);if(!p)return false;show({...p,__dbId:Number(d.id),image_url:d.image_url},{public:true});return true}catch{return false}}
async function openCatalog(id){const p=(window.FUTUROLOGIO_PRODUCTS||[]).find(x=>String(x.id)===String(id));if(!p)return;try{const d=await fetch(API+'/api/explore?mode=recent&limit=24').then(r=>r.json());const row=(d.items||[]).find(x=>String(x.source_id)===String(id));if(row){show({...p,__dbId:Number(row.id),image_url:row.image_url},{public:true});return}}catch{}show(p,{public:true})}
async function load(){try{const products=await fetch('./catalog.json').then(r=>r.json());window.FUTUROLOGIO_PRODUCTS=products;renderCats();const q=new URLSearchParams(location.search),db=q.get('db_invention'),catalog=q.get('invention');if(db){await openDb(db);return}if(catalog)await openCatalog(catalog)}catch(e){console.error('FUTUROLOGIO creation core',e)}}
installImpactStyle();load();
})();
