(()=>{
'use strict';
if(window.__FUTUROLOGIO_CREATION_CORE)return;
window.__FUTUROLOGIO_CREATION_CORE=true;
const API='https://motor-invencoes.edsonfernandesvet.workers.dev';
const CATS=['Casa','Comida & Cozinha','Transporte','Moda','Animais','Tecnologia','Mente & Comportamento','Meio Ambiente','Escola & Trabalho','Espaço','Sem sentido','Tecnologia do futuro','Indústria','Esportes','Entretenimento','Dinheiro & Negócios','Cidade','Agricultura','Viagem','Comunicação','Energia','Tempo & Clima','Objetos pessoais','Lazer','Museu','Bizarro ou Nojento'];
let selected='Casa',used=[],impactAudioCtx=null;
try{used=JSON.parse(localStorage.getItem('futuro_used_v3')||'[]')}catch{}
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function sectionHTML(v,label){if(!v)return '<p>Não informado no lote.</p>';if(Array.isArray(v))return v.map(x=>'<div class="techItem"><span class="techLabel">'+esc(label)+'</span><b>'+esc(x.name||x.title||'Tecnologia')+'</b><p>'+esc(x.description||x.what||x.text||'')+'</p></div>').join('');return '<p>'+esc(v)+'</p>'}
function score(p){const t=(p.realTech||'').length,s=(p.specTech||'').length,i=(p.inventedTech||'').length;let a=Math.max(10,Math.min(70,Math.round(t/(t+s+i||1)*100))),b=Math.max(5,Math.min(50,Math.round(s/(t+s+i||1)*100))),c=100-a-b;if(c<10){c=10;a=Math.max(10,100-b-c)}return[a,b,c]}
function renderCats(){const el=$('cats');if(!el||el.dataset.coreReady)return;el.dataset.coreReady='1';el.innerHTML='';CATS.forEach(c=>{const b=document.createElement('button');b.className='cat'+(c===selected?' selected':'');b.textContent=c;b.onclick=()=>{selected=c;$('selectedCat').textContent=c;document.querySelectorAll('.cat').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')};el.appendChild(b)})}
function addHistory(p){if(!p?.id)return;used=used.filter(x=>x!==p.id);used.push(p.id);localStorage.setItem('futuro_used_v3',JSON.stringify(used));const h=$('history');if(!h)return;h.innerHTML='';used.slice(-12).reverse().forEach(id=>{const q=window.FUTUROLOGIO_PRODUCTS?.find(x=>x.id===id);if(q){const s=document.createElement('span');s.textContent=q.name;h.appendChild(s)}})}
function installImpactStyle(){if(document.getElementById('futuroImpactStyle'))return;const s=document.createElement('style');s.id='futuroImpactStyle';s.textContent='@keyframes futuroCreationShake{0%,100%{transform:translate3d(0,0,0)}12%{transform:translate3d(-8px,2px,0)}25%{transform:translate3d(7px,-2px,0)}38%{transform:translate3d(-6px,1px,0)}52%{transform:translate3d(5px,-1px,0)}66%{transform:translate3d(-3px,0,0)}82%{transform:translate3d(1px,0,0)}}.futuro-creation-shake{animation:futuroCreationShake .46s cubic-bezier(.36,.07,.19,.97) both}';document.head.appendChild(s)}
function creationImpact(){try{const AC=window.AudioContext||window.webkitAudioContext;if(AC){impactAudioCtx=impactAudioCtx||new AC();const ctx=impactAudioCtx;if(ctx.state==='suspended')ctx.resume();const now=ctx.currentTime,duration=.42,buffer=ctx.createBuffer(1,Math.floor(ctx.sampleRate*duration),ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++){const t=i/data.length;data[i]=(Math.random()*2-1)*(1-t)*(1-t)}const noise=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();noise.buffer=buffer;filter.type='lowpass';filter.frequency.setValueAtTime(1800,now);filter.frequency.exponentialRampToValueAtTime(180,now+duration);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.65,now+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);noise.connect(filter).connect(gain).connect(ctx.destination);noise.start(now);noise.stop(now+duration);const osc=ctx.createOscillator(),og=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(110,now);osc.frequency.exponentialRampToValueAtTime(38,now+.28);og.gain.setValueAtTime(.0001,now);og.gain.exponentialRampToValueAtTime(.45,now+.01);og.gain.exponentialRampToValueAtTime(.0001,now+.32);osc.connect(og).connect(ctx.destination);osc.start(now);osc.stop(now+.34)}}catch{}try{const target=document.body;target.classList.remove('futuro-creation-shake');void target.offsetWidth;target.classList.add('futuro-creation-shake');setTimeout(()=>target.classList.remove('futuro-creation-shake'),500)}catch{}}
function propagandaText(p){
 const name=String(p?.name||'esta invenção').trim(),cat=String(p?.category||'').trim();
 const seed=[...name].reduce((a,c)=>((a*31+c.charCodeAt(0))>>>0),cat.length*97);
 const a=['Só as Indústrias FUTUROLOGIO™ teriam a coragem científica de olhar para uma necessidade completamente discutível e concluir: “isso precisa de um produto imediatamente.”','Depois de anos pesquisando problemas que ninguém pediu para resolver, o Departamento de Soluções Desnecessárias da FUTUROLOGIO™ finalmente apresenta uma resposta para este produto.','Os pesquisadores da FUTUROLOGIO™ descobriram que a humanidade poderia viver perfeitamente sem este produto. Foi exatamente por isso que decidiram fabricá-lo.','A engenharia convencional perguntou “por quê?”. A FUTUROLOGIO™ perguntou “e se fizéssemos mesmo assim?”. O resultado atende pelo nome deste produto.'];
 const b=['Testado em condições rigorosamente questionáveis, ele promete acrescentar uma quantidade cientificamente difícil de justificar à sua rotina.','Sua eficiência foi avaliada por especialistas altamente qualificados em parecerem convencidos durante reuniões que poderiam ter sido um e-mail.','A diretoria garante que o investimento em pesquisa foi absolutamente necessário, embora ninguém do financeiro tenha conseguido explicar para quê.','Após uma sequência de testes, simulações e decisões ruins, a equipe declarou o produto “pronto para complicar a vida do consumidor”.'];
 const c=['É a prova de que inovação não precisa melhorar o mundo; às vezes basta tornar o cotidiano mais estranho.','Porque esperar que a vida resolva seus próprios problemas quando uma equipe inteira pode inventar outro problema para vender junto?','Não prometemos que você precisava disso. Prometemos apenas que, depois de conhecer a invenção, será difícil explicar por que ela não existia antes.','Uma conquista tecnológica cuja principal aplicação é permitir que você conte esta história e seja imediatamente desacreditado.'];
 return a[seed%a.length]+' '+b[(seed>>>3)%b.length]+' '+c[(seed>>>6)%c.length]+(cat?' Área de especialização: '+cat+'.':'');
}
function renderPropaganda(p){const result=$('result'),anchor=$('what')?.closest('.card');if(!result||result.classList.contains('hidden')||!anchor)return;let box=document.getElementById('futuroPropagandaBox');if(!box){box=document.createElement('div');box.id='futuroPropagandaBox';box.className='card';box.style.cssText='margin:20px 0 12px;background:#d8ff55;border:2px solid #171717;border-radius:15px;padding:17px;box-shadow:4px 4px 0 #171717';box.innerHTML='<div style="font-size:10px;font-weight:950;letter-spacing:.12em;text-transform:uppercase;margin-bottom:7px">PUBLICIDADE INSTITUCIONAL // FUTUROLOGIO™</div><p id="futuroPropagandaText" style="margin:0;font-size:15px;line-height:1.55;font-weight:750"></p>';anchor.parentElement.insertBefore(box,anchor)}$('futuroPropagandaText').textContent=propagandaText(p)}
function creatorData(p){if(p?.__creator?.id)return p.__creator;try{const u=JSON.parse(localStorage.getItem('futuro_social_user')||'null');return u?.id?u:null}catch{return null}}
function renderCreator(p){const panel=$('result')?.querySelector('.panel');if(!panel)return;let box=document.getElementById('creatorProfileBox');if(!box){box=document.createElement('div');box.id='creatorProfileBox';box.style.cssText='display:flex;align-items:center;justify-content:space-between;gap:10px;margin:6px 0 14px;padding:9px 11px;border:1.5px solid #171717;border-radius:11px;background:#fff';panel.querySelector('#name')?.insertAdjacentElement('afterend',box)}const c=creatorData(p);if(!c){box.remove();return}const avatar=c.avatar?'<img src="'+esc(c.avatar)+'" alt="" style="width:28px;height:28px;border-radius:8px;object-fit:cover;border:1px solid #171717">':'';box.innerHTML='<span style="display:flex;align-items:center;gap:8px;min-width:0">'+avatar+'<b style="font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">Criado por @'+esc(c.username||'criador')+'</b></span><a href="./profile.html?user='+encodeURIComponent(c.id)+'" style="border:1.5px solid #171717;background:#d8ff55;color:#171717;border-radius:9px;padding:7px 9px;text-decoration:none;font:inherit;font-size:10px;font-weight:900;white-space:nowrap">VER PERFIL</a>'}
function show(p,opts={}){if(!p)return;window.FUTUROLOGIO_CURRENT_PRODUCT=p;window.FUTUROLOGIO_CURRENT_DB_ID=Number(p.__dbId||0);renderCreator(p);$('result')?.classList.remove('hidden');['name','subtitle','readiness','year','patent','build','uses','danger','test','curiosity'].forEach(k=>{const el=$(k);if(el)el.textContent=p[k==='danger'?'dangers':k==='test'?'tests':k]||'Não informado no lote.'});if($('intro'))$('intro').textContent=p.what||'Não informado no lote.';if($('what'))$('what').textContent=p.what||'Não informado no lote.';if($('real'))$('real').innerHTML=sectionHTML(p.realTech,'Real');if($('spec'))$('spec').innerHTML=sectionHTML(p.specTech,'Especulativa');if($('imp'))$('imp').textContent=p.inventedTech||'Não informado no lote.';const q=score(p);['r','s','i'].forEach((id,n)=>{if($(id))$(id).style.width=q[n]+'%'});if($('reality'))$('reality').textContent=q[0]+'% baseado em tecnologia existente, '+q[1]+'% especulativo e '+q[2]+'% totalmente inventado.';if($('stamp'))$('stamp').textContent='Registro FUT-'+String(p.id||'').toUpperCase()+'-'+Date.now().toString(36).toUpperCase();renderPropaganda(p);if(!opts.public){addHistory(p);window.FUTUROLOGIO_AFTER_CREATE?.(p);creationImpact()}setTimeout(()=>{renderCreator(p);renderPropaganda(p);window.scrollTo({top:($('result')?.offsetTop||0)-15,behavior:'smooth'})},20)}
window.show=show;
window.newInvention=async function(){const pool=(window.FUTUROLOGIO_PRODUCTS||[]).filter(p=>p.category===selected&&!used.includes(p.id));if(!pool.length){alert('Essa categoria já mostrou todos os produtos disponíveis. Escolha outra categoria.');return}show(pool[Math.floor(Math.random()*pool.length)])};
async function openDb(id){try{const d=await fetch(API+'/api/invention/'+encodeURIComponent(id)).then(r=>r.json());if(!d.ok)return false;const p=(window.FUTUROLOGIO_PRODUCTS||[]).find(x=>String(x.id)===String(d.source_id))||(window.FUTUROLOGIO_PRODUCTS||[]).find(x=>x.name===d.name);if(!p)return false;show({...p,__dbId:Number(d.id),image_url:d.image_url,__creator:d.user},{public:true});return true}catch{return false}}
async function openCatalog(id){const p=(window.FUTUROLOGIO_PRODUCTS||[]).find(x=>String(x.id)===String(id));if(!p)return;try{const d=await fetch(API+'/api/explore?mode=recent&limit=24').then(r=>r.json());const row=(d.items||[]).find(x=>String(x.source_id)===String(id));if(row){show({...p,__dbId:Number(row.id),image_url:row.image_url,__creator:{id:row.user_id,username:row.username,avatar:row.avatar}},{public:true});return}}catch{}show(p,{public:true})}
async function load(){try{const products=await fetch('./catalog.json').then(r=>r.json());window.FUTUROLOGIO_PRODUCTS=products;renderCats();const q=new URLSearchParams(location.search),db=q.get('db_invention'),catalog=q.get('invention');if(db){await openDb(db);return}if(catalog)await openCatalog(catalog)}catch(e){console.error('FUTUROLOGIO creation core',e)}}
installImpactStyle();load();
})();