(()=>{
'use strict';
if(window.__FUTURO_CREDITS_V1)return;
window.__FUTURO_CREDITS_V1=true;
const API='https://motor-invencoes.edsonfernandesvet.workers.dev',TK='futuro_auth_token',UK='futuro_social_user';
const qs=new URLSearchParams(location.search);
if(qs.has('user'))return;
const token=()=>localStorage.getItem(TK)||'';
const user=()=>{try{return JSON.parse(localStorage.getItem(UK)||'null')}catch{return null}};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function css(){if($('#creditsStyle'))return;const s=document.createElement('style');s.id='creditsStyle';s.textContent=`.fc-box{margin:18px 0;border:2px solid #171717;border-radius:18px;background:#fffdf8;padding:16px;box-shadow:4px 4px 0 #171717}.fc-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.fc-title{font-size:15px;font-weight:950}.fc-total{display:flex;align-items:baseline;gap:5px}.fc-total strong{font-size:28px;letter-spacing:-.04em}.fc-total span{font-size:10px;color:#6f6b63}.fc-sub{margin:3px 0 14px;color:#6f6b63;font-size:10px}.fc-missions{display:grid;grid-template-columns:1fr 1fr;gap:9px}.fc-mission{border:1px solid #ded8ca;border-radius:13px;background:#fff;padding:11px}.fc-mission.done{border-color:#171717;background:#f7ffd9}.fc-mission-top{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.fc-mission b{font-size:11px}.fc-mission small{display:block;color:#6f6b63;font-size:9px;margin-top:3px}.fc-progress{height:8px;border:1px solid #171717;border-radius:99px;overflow:hidden;background:#f3f0e7;margin:9px 0}.fc-progress i{display:block;height:100%;background:#d8ff55}.fc-mission button{width:100%;border:1.5px solid #171717;border-radius:9px;background:#fff;padding:8px;font:inherit;font-size:10px;font-weight:950;cursor:pointer}.fc-mission button.ready{background:#d8ff55}.fc-mission button:disabled{opacity:.55;cursor:default}.fc-status{margin-top:10px;min-height:14px;font-size:10px;color:#6f6b63}.fc-status.ok{color:#27722f}.fc-status.err{color:#b3261e}.fc-legend{display:flex;justify-content:space-between;gap:10px;margin-top:12px;padding-top:10px;border-top:1px solid #ded8ca;font-size:9px;color:#6f6b63}.fc-legend b{color:#171717}@media(max-width:650px){.fc-missions{grid-template-columns:1fr}.fc-head{align-items:flex-start}}`;
document.head.appendChild(s)}
function host(){if(location.pathname.endsWith('/criar.html')||location.pathname==='/criar.html')return $('#createBtn')?.closest('.area');if(location.pathname.endsWith('/profile.html')||location.pathname==='/profile.html')return $('#profilePage');return $('.hero')}
function existing(){return $('#futuroCreditsBox')}
function build(){if(existing()||!token())return null;const h=host();if(!h)return null;const box=document.createElement('section');box.id='futuroCreditsBox';box.className='fc-box';box.innerHTML='<div class="fc-head"><div><div class="fc-title">CRÉDITOS DE HOJE</div><div class="fc-sub">3 créditos diários + até 2 créditos por missões</div></div><div class="fc-total"><strong id="fcTotal">—</strong><span>disponíveis</span></div></div><div class="fc-missions"><div class="fc-mission" data-mission="likes"><div class="fc-mission-top"><div><b>Dar 3 curtidas</b><small>Em invenções de outros usuários</small></div><b class="fc-prog">0/3</b></div><div class="fc-progress"><i style="width:0%"></i></div><button type="button">VERIFICAR</button></div><div class="fc-mission" data-mission="comment"><div class="fc-mission-top"><div><b>Fazer 1 comentário</b><small>Em uma invenção de outro usuário</small></div><b class="fc-prog">0/1</b></div><div class="fc-progress"><i style="width:0%"></i></div><button type="button">VERIFICAR</button></div></div><div class="fc-status" id="fcStatus"></div><div class="fc-legend"><span>Base diária: <b>3</b></span><span>Bônus conquistados: <b id="fcBonus">0/2</b></span><span>Máximo hoje: <b>5</b></span></div>';
if(location.pathname.endsWith('/criar.html')||location.pathname==='/criar.html')h.appendChild(box);else if(location.pathname.endsWith('/profile.html')||location.pathname==='/profile.html')h.insertAdjacentElement('afterend',box);else h.insertAdjacentElement('afterend',box);
box.querySelectorAll('[data-mission]').forEach(card=>{card.querySelector('button').onclick=()=>claim(card.dataset.mission)});return box}
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{'content-type':'application/json',...(opt.headers||{}),Authorization:'Bearer '+token()}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.error||'Não foi possível carregar os créditos.'),{data:d,status:r.status});return d}
function render(d){const box=build();if(!box)return;$('#fcTotal').textContent=Number(d.credits||0);$('#fcBonus').textContent=Number(d.extra||0)+'/2';[['likes','likes'],['comment','comment']].forEach(([key,id])=>{const m=d.missions?.[id],card=box.querySelector('[data-mission="'+key+'"]');if(!m||!card)return;const p=Math.min(Number(m.target||1),Number(m.progress||0)),target=Number(m.target||1),done=!!m.rewarded;card.classList.toggle('done',done);card.querySelector('.fc-prog').textContent=p+'/'+target;card.querySelector('.fc-progress i').style.width=(Math.round(p/target*100))+'%';const b=card.querySelector('button');b.disabled=done;b.classList.toggle('ready',!done&&p>=target);b.textContent=done?'CONCLUÍDA':'RESGATAR +1 CRÉDITO';});const create=$('#createBtn');if(create&&!d.credits)create.title='Sem créditos disponíveis. Complete as missões para ganhar até +2.';window.FUTUROLOGIO_CREDITS_STATE=d}
async function load(){if(!token()||!user())return;try{const d=await api('/api/credit-status?_='+Date.now(),{cache:'no-store'});render(d)}catch{}}
async function claim(type){const box=existing();if(!box)return;const card=box.querySelector('[data-mission="'+type+'"]'),btn=card.querySelector('button'),st=$('#fcStatus');btn.disabled=true;st.textContent='VERIFICANDO MISSÃO…';st.className='fc-status';try{const d=await api('/api/claim-credit-mission',{method:'POST',body:JSON.stringify({type})});st.textContent=d.awarded?'MISSÃO CONCLUÍDA! +1 crédito':'Missão já concluída.';st.className='fc-status ok';if(d.user)localStorage.setItem(UK,JSON.stringify({...user(),...d.user}));render(d)}catch(e){const d=e.data||{};st.textContent=e.message||'Missão ainda não concluída.';st.className='fc-status err';if(d.missions)render({credits:d.credits??window.FUTUROLOGIO_CREDITS_STATE?.credits??0,extra:d.allowance?.credits??window.FUTUROLOGIO_CREDITS_STATE?.extra??0,missions:d.missions});}finally{const b=box.querySelector('[data-mission="'+type+'"] button');if(b)b.disabled=!!box.querySelector('[data-mission="'+type+'"]')?.classList.contains('done')}}
window.FUTUROLOGIO_CHECK_REWARDS=load;
css();load();setInterval(load,15000);
})();
