(()=>{
'use strict';
if(window.__FUTURO_CREDITS_V3)return;
window.__FUTURO_CREDITS_V3=true;
const API='https://motor-invencoes.edsonfernandesvet.workers.dev',TK='futuro_auth_token',UK='futuro_social_user';
const qs=new URLSearchParams(location.search);if(qs.has('user'))return;
const token=()=>localStorage.getItem(TK)||'';const user=()=>{try{return JSON.parse(localStorage.getItem(UK)||'null')}catch{return null}};const $=s=>document.querySelector(s);
function css(){if($('#creditsStyle'))return;const s=document.createElement('style');s.id='creditsStyle';s.textContent=`.fc-box{margin:10px 0;border:1.5px solid #171717;border-radius:12px;background:#fffdf8;padding:9px 10px;box-shadow:2px 2px 0 #171717}.fc-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.fc-title{font-size:12px;font-weight:950}.fc-sub{margin:2px 0 7px;color:#6f6b63;font-size:8px}.fc-total{display:flex;align-items:baseline;gap:3px}.fc-total strong{font-size:22px;letter-spacing:-.04em}.fc-total span{font-size:8px;color:#6f6b63}.fc-missions{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.fc-mission{border:1px solid #ded8ca;border-radius:9px;background:#fff;padding:7px;min-width:0}.fc-mission.done{border-color:#171717;background:#f7ffd9}.fc-mission-top{display:flex;justify-content:space-between;gap:4px;align-items:flex-start}.fc-mission b{font-size:9px;line-height:1.15}.fc-mission small{display:block;color:#6f6b63;font-size:7px;margin-top:2px;line-height:1.15}.fc-progress{height:5px;border:1px solid #171717;border-radius:99px;overflow:hidden;background:#f3f0e7;margin:5px 0}.fc-progress i{display:block;height:100%;background:#d8ff55}.fc-mission button{width:100%;border:1px solid #171717;border-radius:7px;background:#fff;padding:5px 3px;font:inherit;font-size:8px;font-weight:950;cursor:pointer;line-height:1}.fc-mission button.ready{background:#d8ff55}.fc-mission button:disabled{opacity:.55;cursor:default}.fc-status{margin-top:6px;min-height:11px;font-size:8px;color:#6f6b63}.fc-status.ok{color:#27722f}.fc-status.err{color:#b3261e}.fc-legend{display:flex;justify-content:space-between;gap:6px;margin-top:7px;padding-top:6px;border-top:1px solid #ded8ca;font-size:7px;color:#6f6b63}.fc-legend b{color:#171717}@media(max-width:430px){.fc-box{padding:8px}.fc-missions{gap:4px}.fc-mission{padding:6px}.fc-mission b{font-size:8px}.fc-mission small{font-size:6.5px}.fc-mission button{font-size:7px;padding:5px 1px}.fc-legend{font-size:6.5px}}`;
document.head.appendChild(s)}
function host(){if(location.pathname.endsWith('/criar.html')||location.pathname==='/criar.html')return $('#createBtn')?.closest('.area')||$('#createBtn')?.parentElement;if(location.pathname.endsWith('/profile.html')||location.pathname==='/profile.html')return $('#profilePage')||document.querySelector('main');return $('.hero')||document.querySelector('main')}
function existing(){return $('#futuroCreditsBox')}
function build(){if(existing()||!token())return null;const h=host();if(!h)return null;const box=document.createElement('section');box.id='futuroCreditsBox';box.className='fc-box';box.innerHTML='<div class="fc-head"><div><div class="fc-title">CRÉDITOS DE HOJE</div><div class="fc-sub">3 créditos + até 3 bônus por missões</div></div><div class="fc-total"><strong id="fcTotal">—</strong><span>disponíveis</span></div></div><div class="fc-missions"><div class="fc-mission" data-mission="likes"><div class="fc-mission-top"><div><b>3 curtidas</b><small>Em produtos de outros</small></div><b class="fc-prog">0/3</b></div><div class="fc-progress"><i style="width:0%"></i></div><button type="button">RESGATAR +1</button></div><div class="fc-mission" data-mission="comment"><div class="fc-mission-top"><div><b>1 comentário</b><small>Em produto de outro usuário</small></div><b class="fc-prog">0/1</b></div><div class="fc-progress"><i style="width:0%"></i></div><button type="button">RESGATAR +1</button></div><div class="fc-mission" data-mission="share"><div class="fc-mission-top"><div><b>3 compartilhamentos</b><small>Produtos de outros usuários</small></div><b class="fc-prog">0/3</b></div><div class="fc-progress"><i style="width:0%"></i></div><button type="button">RESGATAR +1</button></div></div><div class="fc-status" id="fcStatus"></div><div class="fc-legend"><span>Base <b>3</b></span><span>Bônus <b id="fcBonus">0/3</b></span><span>Máx. <b>6</b></span></div>';
if(location.pathname.endsWith('/criar.html')||location.pathname==='/criar.html')h.appendChild(box);else h.insertAdjacentElement('afterend',box);box.querySelectorAll('[data-mission]').forEach(card=>{card.querySelector('button').onclick=()=>claim(card.dataset.mission)});return box}
async function api(path,opt={}){const r=await fetch(API+path,{...opt,cache:'no-store',headers:{'content-type':'application/json',...(opt.headers||{}),Authorization:'Bearer '+token()}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.error||'Não foi possível carregar os créditos.'),{data:d,status:r.status});return d}
function render(d){const box=build();if(!box)return;$('#fcTotal').textContent=Number(d.credits||0);$('#fcBonus').textContent=Number(d.extra||0)+'/3';[['likes','likes'],['comment','comment'],['share','share']].forEach(([key,id])=>{const m=d.missions?.[id],card=box.querySelector('[data-mission="'+key+'"]');if(!m||!card)return;const p=Math.min(Number(m.target||1),Number(m.progress||0)),target=Number(m.target||1),done=!!m.rewarded;card.classList.toggle('done',done);card.querySelector('.fc-prog').textContent=p+'/'+target;card.querySelector('.fc-progress i').style.width=Math.round(p/target*100)+'%';const b=card.querySelector('button');b.disabled=done;b.classList.toggle('ready',!done&&p>=target);b.textContent=done?'CONCLUÍDA':'RESGATAR +1'})}
async function load(){if(!token()||!user())return;try{render(await api('/api/credit-status?_='+Date.now()))}catch(e){if(!existing())build()}}
async function claim(type){const box=existing();if(!box)return;const card=box.querySelector('[data-mission="'+type+'"]'),btn=card.querySelector('button'),st=$('#fcStatus');btn.disabled=true;st.textContent='VERIFICANDO…';st.className='fc-status';try{const d=await api('/api/claim-credit-mission',{method:'POST',body:JSON.stringify({type})});st.textContent=d.awarded?'MISSÃO CONCLUÍDA! +1':'Missão ainda não concluída.';st.className='fc-status ok';render(d)}catch(e){st.textContent=e.message||'Missão ainda não concluída.';st.className='fc-status err';if(e.data?.missions)render(e.data)}finally{load()}}
css();build();load();setInterval(load,5000);
})();
