// FUTUROLOGIO community discovery gallery
(() => {
  'use strict';
  const API='https://motor-invencoes.edsonfernandesvet.workers.dev';
  const token=()=>localStorage.getItem('futuro_auth_token')||'';
  const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const mediaUrl=v=>{const s=String(v||'').trim();return s?(s.startsWith('http://')||s.startsWith('https://')?s:API+(s.startsWith('/')?s:'/'+s)):''};
  const css=`.ft-explore{max-width:1120px;margin:26px auto 34px;padding:0 20px}.ft-explore-head{display:flex;justify-content:space-between;align-items:end;gap:12px;flex-wrap:wrap;margin-bottom:14px}.ft-explore-kicker{font-size:10px;font-weight:1000;letter-spacing:.16em;color:#62e6ff}.ft-explore h2{margin:4px 0;color:#fff;font-size:28px}.ft-explore p{margin:0;color:#9aa7c2;font-size:12px}.ft-explore-tabs{display:flex;gap:7px;flex-wrap:wrap}.ft-explore-tab{border:1px solid #405476;border-radius:10px;background:#0b1427;color:#dce6ff;padding:8px 11px;font-weight:900;font-size:10px;cursor:pointer}.ft-explore-tab.on{background:#d8ff55;color:#091007;border-color:#fff}.ft-explore-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}.ft-explore-card{background:linear-gradient(145deg,#10172a,#151e35);border:2px solid #2a3858;border-radius:16px;overflow:hidden;box-shadow:0 8px 0 #050710;cursor:pointer;transition:transform .15s,border-color .15s}.ft-explore-card:hover{transform:translateY(-3px);border-color:#62e6ff}.ft-explore-img{aspect-ratio:16/9;background:radial-gradient(circle,#24395c,#0b1120 70%);display:grid;place-items:center;color:#9eb1d0;font-size:10px;text-align:center;padding:10px}.ft-explore-img img{width:100%;height:100%;object-fit:cover}.ft-explore-body{padding:12px}.ft-explore-cat{display:inline-block;font-size:8px;font-weight:1000;letter-spacing:.1em;text-transform:uppercase;color:#07101a;background:#62e6ff;border-radius:99px;padding:4px 7px}.ft-explore-name{margin:8px 0 4px;color:#fff;font-size:16px;font-weight:1000}.ft-explore-creator{color:#aebbd2;font-size:10px}.ft-explore-creator b{color:#d8ff55}.ft-explore-meta{display:flex;gap:10px;margin-top:9px;color:#7f91af;font-size:9px;font-weight:900}.ft-explore-meta b{color:#fff}.ft-my{margin-top:24px}.ft-my-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:9px}.ft-my-title h3{margin:0;color:#fff;font-size:17px}.ft-explore-empty{padding:18px;border:1px dashed #3b537a;border-radius:13px;color:#9eb1d0;font-size:11px;background:#0b1222}.ft-explore-loading{color:#9eb1d0;font-size:11px;padding:18px 0}@media(max-width:850px){.ft-explore-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.ft-explore{padding:0 12px}.ft-explore-grid{grid-template-columns:1fr}}`;
  const style=document.createElement('style');style.id='futuro-explore-ui';style.textContent=css;document.head.appendChild(style);
  async function get(path){const h={};if(token())h.Authorization='Bearer '+token();const r=await fetch(API+path,{headers:h});if(!r.ok)throw new Error('Falha ao carregar a invenção');return r.json()}

  async function waitForShow(timeout=7000){const start=Date.now();while(typeof window.show!=='function'&&Date.now()-start<timeout)await new Promise(r=>setTimeout(r,100));return typeof window.show==='function'}
  function paintImage(id,p){const src=mediaUrl(p?.image_url);if(!src)return;const start=Date.now();const timer=setInterval(()=>{const card=document.querySelector('.game-image-card');const ph=card?.querySelector('.game-image-placeholder');if(card&&ph){const img=document.createElement('img');img.alt=p.name||'Imagem da invenção';img.src=src;ph.replaceWith(img);clearInterval(timer);return}if(Date.now()-start>8000)clearInterval(timer)},100)}

  async function openInvention(id){
    const dbId=Number(id);if(!dbId||window.__FUTUROLOGIO_OPENING_ID===dbId)return;window.__FUTUROLOGIO_OPENING_ID=dbId;
    try{
      const d=await get('/api/invention/'+encodeURIComponent(dbId));
      const list=window.FUTUROLOGIO_PRODUCTS||window.PRODUCTS||[];
      let p=d.source_id!=null?list.find(x=>String(x.id)===String(d.source_id)):null;
      if(!p){const data=d.data||{};p={id:d.source_id||('db-'+d.id),name:d.name,category:d.category,subtitle:data.subtitle||'',what:data.what||d.concept||'',realTech:data.realTech||'',specTech:data.specTech||'',inventedTech:data.inventedTech||'',build:data.build||'',uses:data.uses||'',dangers:data.dangers||'',test:data.test||'',tests:data.test||'',curiosity:data.curiosity||'',readiness:data.readiness||'',year:data.year||'',patent:data.patent||''}}else p={...p};
      p.image_url=mediaUrl(d.image_url||p.image_url);p.__dbId=dbId;
      window.FUTUROLOGIO_CURRENT_PRODUCT=p;window.FUTUROLOGIO_CURRENT_DB_ID=dbId;window.FUTUROLOGIO_DB_ID_FOR=()=>dbId;
      if(!await waitForShow())throw new Error('A tela de invenção não carregou a tempo.');
      window.show(p);paintImage(dbId,p);document.getElementById('result')?.scrollIntoView({behavior:'smooth',block:'start'});
    }catch(e){console.warn('[FUTUROLOGIO] open invention failed',e);alert(e?.message||'Não foi possível abrir esta invenção.')}finally{setTimeout(()=>{if(window.__FUTUROLOGIO_OPENING_ID===dbId)window.__FUTUROLOGIO_OPENING_ID=0},300)}
  }
  function card(x){const src=mediaUrl(x.image_url);return `<article class="ft-explore-card" data-db-id="${x.id}" role="button" tabindex="0"><div class="ft-explore-img">${src?`<img src="${esc(src)}" alt="${esc(x.name)}">`:'IMAGEM AINDA NÃO ENVIADA'}</div><div class="ft-explore-body"><span class="ft-explore-cat">${esc(x.category)}</span><div class="ft-explore-name">${esc(x.name)}</div><div class="ft-explore-creator">Criado por <b>${esc(x.username)}</b></div><div class="ft-explore-meta"><span>♥ <b>${x.likes||0}</b></span><span>✎ <b>${x.comments||0}</b></span></div></div></article>`}
  function bindCards(root){root.querySelectorAll('.ft-explore-card').forEach(c=>{if(c.dataset.bound)return;c.dataset.bound='1';const open=()=>{const id=Number(c.dataset.dbId);if(!id)return;history.replaceState(null,'','?db_invention='+encodeURIComponent(id));openInvention(id)};c.addEventListener('click',open);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
  async function load(mode){const grid=document.getElementById('ftExploreGrid');if(!grid)return;grid.innerHTML='<div class="ft-explore-loading">Carregando…</div>';try{const d=await get('/api/explore?mode='+encodeURIComponent(mode)+'&limit=12');grid.innerHTML=d.items?.length?d.items.map(card).join(''):'<div class="ft-explore-empty">Ainda não há invenções nesta seleção.</div>';bindCards(grid)}catch{grid.innerHTML='<div class="ft-explore-empty">A galeria estará disponível assim que o catálogo social estiver conectado.</div>'}}
  async function loadMine(){const wrap=document.getElementById('ftMy');if(!wrap||!token()){wrap?.remove();return}try{const d=await get('/api/my-inventions?limit=12');const grid=document.getElementById('ftMyGrid');if(!grid)return;grid.innerHTML=d.items?.length?d.items.map(card).join(''):'<div class="ft-explore-empty">Você ainda não tem invenções registradas.</div>';bindCards(grid)}catch{wrap.remove()}}
  function mount(){if(document.getElementById('ftExplore'))return;const hero=document.querySelector('.hero');if(!hero)return;const section=document.createElement('section');section.className='ft-explore';section.id='ftExplore';section.innerHTML='<div class="ft-explore-head"><div><div class="ft-explore-kicker">GALERIA DA COMUNIDADE</div><h2>Descubra as invenções</h2><p>Veja o que a comunidade está inventando e entre no perfil de cada criador.</p></div><div class="ft-explore-tabs"><button class="ft-explore-tab on" data-mode="recent">Últimas criações</button><button class="ft-explore-tab" data-mode="week">Mais curtidas da semana</button></div></div><div id="ftExploreGrid" class="ft-explore-grid"><div class="ft-explore-loading">Carregando invenções…</div></div><div class="ft-my" id="ftMy"><div class="ft-my-title"><h3>Meu laboratório</h3></div><div id="ftMyGrid" class="ft-explore-grid"></div></div>';hero.insertAdjacentElement('afterend',section);section.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{section.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('on'));b.classList.add('on');load(b.dataset.mode)});load('recent');loadMine()}
  const timer=setInterval(()=>{if(document.body&&document.querySelector('.hero')){clearInterval(timer);mount();const id=new URLSearchParams(location.search).get('db_invention');if(id)openInvention(id)}},80);
})();
