(() => {
  'use strict';
  const css = `
  :root{--game-bg:#080b16;--game-panel:#10172a;--game-panel-2:#151e35;--game-ink:#f7f8ff;--game-muted:#9aa7c2;--game-lime:#d8ff55;--game-cyan:#62e6ff;--game-pink:#ff62c6;--game-gold:#ffd34e;--game-line:#2a3858;--game-shadow:0 14px 0 #050710,0 18px 35px rgba(0,0,0,.28)}
  body.game-mode{background:radial-gradient(circle at 50% -10%,#26375d 0,#10172a 30%,#080b16 72%);color:var(--game-ink);min-height:100vh;background-attachment:fixed}
  body.game-mode:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.18;background-image:linear-gradient(rgba(98,230,255,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(98,230,255,.08) 1px,transparent 1px);background-size:34px 34px;mask-image:linear-gradient(to bottom,#000,transparent 85%);z-index:-1}
  .game-mode header{background:rgba(8,11,22,.88);border-bottom:2px solid var(--game-cyan);box-shadow:0 4px 22px rgba(98,230,255,.12);backdrop-filter:blur(12px)}
  .game-mode .logo{color:white;text-shadow:0 0 18px rgba(98,230,255,.45);letter-spacing:.02em}.game-mode .logo span{background:var(--game-pink);color:#160b19;border-color:#fff;box-shadow:3px 3px 0 #fff}
  .game-mode main{max-width:1120px}.game-mode .hero{padding:48px 0 34px}.game-mode .kicker{color:var(--game-cyan);letter-spacing:.2em}.game-mode .hero h1{color:white;text-shadow:0 5px 0 #29365b,0 0 28px rgba(98,230,255,.18)}.game-mode .hero p{color:var(--game-muted)}
  .game-mode .panel{background:linear-gradient(145deg,var(--game-panel),var(--game-panel-2));border:2px solid var(--game-line);border-radius:18px;box-shadow:var(--game-shadow);color:var(--game-ink);position:relative;overflow:hidden}.game-mode .panel:before{content:"";position:absolute;left:0;top:0;width:100%;height:3px;background:linear-gradient(90deg,var(--game-cyan),var(--game-pink),var(--game-lime))}.game-mode .panel h2{color:white}.game-mode .panel>p{color:var(--game-muted)}
  .game-mode .cat{background:#0c1324;color:#dce5ff;border-color:var(--game-line);box-shadow:0 4px 0 #070b15;transition:transform .15s,box-shadow .15s,border-color .15s,background .15s}.game-mode .cat:hover{background:#17243e;border-color:var(--game-cyan);transform:translateY(-2px);box-shadow:0 6px 0 #070b15}.game-mode .cat.selected{background:linear-gradient(135deg,var(--game-lime),#a7db39);color:#081006;border-color:white;box-shadow:0 5px 0 #6d8e25}
  .game-mode .selected-label{color:var(--game-muted)}.game-mode .selected-label strong{color:var(--game-cyan)}
  .game-mode .create{background:linear-gradient(90deg,var(--game-pink),#ff8bdf 48%,var(--game-cyan));color:#090b15;border-color:white;box-shadow:0 7px 0 #080b16,0 0 28px rgba(255,98,198,.18);text-transform:uppercase;letter-spacing:.06em;transition:transform .12s,box-shadow .12s}.game-mode .create:hover{transform:translateY(-2px);box-shadow:0 9px 0 #080b16,0 0 34px rgba(98,230,255,.22)}.game-mode .create:active{transform:translateY(3px);box-shadow:0 3px 0 #080b16}
  .game-mode .result .panel{border-color:#3a4d79}.game-mode .tag{background:var(--game-pink);border-color:white;color:#170914;box-shadow:3px 3px 0 #050710}.game-mode .result h2{color:white;text-shadow:0 4px 0 #263456}.game-mode .sub{color:var(--game-cyan)}.game-mode .intro{color:#e8ecf8}.game-mode .fact,.game-mode .card{background:#0b1222;border-color:var(--game-line);color:#edf2ff}.game-mode .fact small{color:var(--game-muted)}.game-mode .fact b{color:white}.game-mode .science{background:linear-gradient(145deg,#0c2030,#0b1222)}.game-mode .spec{background:linear-gradient(145deg,#1d1530,#0b1222)}.game-mode .impossible{background:linear-gradient(145deg,#2b1427,#0b1222)}.game-mode .techItem{background:#111b30;border-color:#2a3858}.game-mode .techItem p{color:#aebbd2}.game-mode .science .techLabel{background:#163c4b;color:var(--game-cyan);border-color:#2b7185}.game-mode .spec .techLabel{background:#34204c;color:#e1a8ff;border-color:#714f8e}
  .game-mode .meter{background:#070b15;border-color:#415173}.game-mode .share{position:sticky;bottom:12px;padding:10px;background:rgba(8,11,22,.82);border:1px solid var(--game-line);border-radius:14px;backdrop-filter:blur(10px);z-index:5}.game-mode .primary{background:var(--game-lime);color:#091007;border-color:white;box-shadow:0 4px 0 #617d20}.game-mode .secondary{background:#101a2e;color:white;border-color:#4b5f86}.game-mode .stamp{border-color:#4b5f86;background:#0b1222;color:#c8d3e9}.game-mode .stamp b{color:var(--game-gold);text-shadow:0 0 12px rgba(255,211,78,.2)}.game-mode .history span{background:#101a2e;color:#dce5ff;border-color:#30415f}.game-mode footer{color:#6f7e9d}
  .game-image-card{margin:0 0 18px;border:2px solid #30415f;border-radius:16px;background:linear-gradient(145deg,#080e1d,#141e35);padding:10px;position:relative;overflow:hidden}.game-image-card:after{content:"VISUAL // PROTÓTIPO";position:absolute;right:12px;top:12px;font-size:9px;font-weight:1000;letter-spacing:.12em;color:#62e6ff;background:#07101e;border:1px solid #34506e;border-radius:99px;padding:5px 8px}.game-image-card img{display:block;width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:10px;background:radial-gradient(circle,#24395c,#0b1120 70%)}.game-image-placeholder{aspect-ratio:16/9;border-radius:10px;display:grid;place-items:center;text-align:center;padding:24px;background:radial-gradient(circle at 50% 40%,#24395c,#0b1120 68%);color:#9eb1d0;border:1px dashed #3b537a}.game-image-placeholder strong{display:block;color:#d8ff55;font-size:15px;margin-bottom:6px}.game-image-placeholder span{font-size:12px;line-height:1.5}.game-image-meta{display:flex;justify-content:space-between;gap:10px;margin:9px 2px 0;color:#7f91af;font-size:10px;text-transform:uppercase;letter-spacing:.08em;font-weight:900}.game-image-meta b{color:#62e6ff}
  .game-prompt-card{margin:20px 0 0;border:2px solid #3b4f78;border-radius:18px;padding:18px;background:linear-gradient(145deg,#0a1222,#18233d);box-shadow:0 8px 0 #050710;color:#edf2ff}.game-prompt-kicker{display:inline-block;font-size:9px;font-weight:1000;letter-spacing:.15em;color:#62e6ff;border:1px solid #31526c;background:#07101c;border-radius:99px;padding:5px 8px}.game-prompt-card h3{margin:9px 0 5px;font-size:21px;color:#fff}.game-prompt-card>p{margin:0 0 14px;color:#aebbd2;font-size:12px;line-height:1.5}.game-style-row{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}.game-style-btn{border:1px solid #405476;border-radius:10px;background:#0b1427;color:#dbe6ff;padding:8px 10px;font-size:10px;font-weight:900;cursor:pointer}.game-style-btn.active{background:#d8ff55;color:#091007;border-color:#fff}.game-prompt-text{width:100%;min-height:190px;resize:vertical;border:1px solid #405476;border-radius:12px;background:#070d19;color:#eaf1ff;padding:12px;font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace;outline:none}.game-prompt-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.game-prompt-copy{background:#62e6ff;color:#07101a;border:1px solid #fff;border-radius:10px;padding:10px 13px;font-weight:1000;cursor:pointer}.game-prompt-note{font-size:9px;color:#7f91af;margin-top:9px}.game-prompt-note b{color:#d8ff55}.game-image-upload{margin-top:12px;border-top:1px solid #30415f;padding-top:12px}.game-image-upload label{display:block;color:#aebbd2;font-size:11px;font-weight:900;margin-bottom:7px}.game-image-upload input{width:100%;font-size:11px;color:#dce6ff}.game-upload-status{font-size:10px;color:#9eb1d0;margin-top:7px}.game-upload-status.ok{color:#d8ff55}.game-upload-status.err{color:#ff8da7}
  @media(max-width:760px){.game-mode .panel{box-shadow:0 9px 0 #050710,0 14px 28px rgba(0,0,0,.24)}.game-mode .hero{padding-top:34px}.game-mode .hero h1{font-size:clamp(48px,15vw,72px)}}`;
  const style=document.createElement('style');style.id='futuro-game-ui';style.textContent=css;document.head.appendChild(style);document.body.classList.add('game-mode');

  function currentProduct(){const name=document.getElementById('name')?.textContent?.trim();if(!name||!Array.isArray(window.FUTUROLOGIO_PRODUCTS))return null;return window.FUTUROLOGIO_PRODUCTS.find(p=>p.name===name)||null}
  function ensureImageCard(){const result=document.getElementById('result');const panel=result?.querySelector('.panel');if(!panel||panel.querySelector('.game-image-card'))return;const card=document.createElement('div');card.className='game-image-card';card.innerHTML='<div class="game-image-placeholder"><div><strong>VISUALIZAÇÃO DA INVENÇÃO</strong><span>A imagem do produto será criada automaticamente por IA.<br>O espaço já está reservado para o render oficial.</span></div></div><div class="game-image-meta"><span>RENDER DO PRODUTO</span><b>IA // EM BREVE</b></div>';const tag=panel.querySelector('.tag');tag?.insertAdjacentElement('afterend',card)}
  function refreshImageCard(){ensureImageCard();const card=document.querySelector('.game-image-card');if(!card)return;const p=currentProduct();if(!p)return;const src=p.image_url||p.imageUrl||p.image;const ph=card.querySelector('.game-image-placeholder');if(src){ph.innerHTML='<img alt="'+String(p.name).replace(/"/g,'&quot;')+'" src="'+String(src).replace(/"/g,'&quot;')+'">';card.querySelector('.game-image-meta b').textContent='RENDER DISPONÍVEL'}}

  const styles={toy:'FUTUROLOGIO 3D TOY-TECH ABSURDO',retro:'FUTUROLOGIO PUBLICIDADE RETRÔ 1980s',comic:'FUTUROLOGIO HQ POP SURREAL'};
  const styleDescriptions={toy:'3D premium de brinquedo colecionável, materiais plásticos e metálicos, iluminação de estúdio, cores neon, design de produto exageradamente sofisticado e humor visual.',retro:'fotografia publicitária fictícia de tecnologia dos anos 1980, estética de catálogo vintage, flash de estúdio, cores saturadas, tipografia retrô e humor absurdo.',comic:'ilustração editorial em estilo HQ pop, linhas marcadas, perspectiva dinâmica, cores vibrantes, onomatopeias discretas e humor físico/cartunesco.'};
  let selectedStyle='toy';
  function buildPrompt(p){if(!p)return '';const clean=v=>String(v||'').replace(/\s+/g,' ').trim();return `Crie uma imagem publicitária oficial de uma invenção fictícia do site FUTUROLOGIO™.\n\nPRODUTO: ${clean(p.name)}\nCATEGORIA: ${clean(p.category)}\nO QUE É: ${clean(p.what)}\nCOMO FUNCIONA: ${clean(p.build)}\nTECNOLOGIAS: ${clean(p.realTech)} ${clean(p.specTech)} ${clean(p.inventedTech)}\n\nESTILO FUTUROLOGIO: ${styleDescriptions[selectedStyle]}\n\nCENA: mostre o produto claramente EM FUNCIONAMENTO, sendo usado por uma pessoa em uma situação cotidiana coerente com sua função. A cena deve ser engraçada, absurda e visualmente fácil de entender, mas o produto deve continuar sendo o protagonista. Mostrar consequências cômicas da invenção sem transformar a imagem em um meme genérico. Composição cinematográfica, enquadramento publicitário, alta qualidade, detalhes ricos, iluminação profissional, aparência de produto real fotografado/renderizado para um catálogo de invenções.\n\nIDENTIDADE VISUAL OBRIGATÓRIA: incluir de forma legível e integrada ao design o nome “${clean(p.name)}” e a assinatura “INVENÇÕES FUTUROLOGIO™”. Não substituir, abreviar ou alterar esses textos. O nome do produto deve aparecer como título de embalagem, placa, tela do produto ou elemento gráfico da publicidade. A assinatura “INVENÇÕES FUTUROLOGIO™” deve aparecer como marca do catálogo.\n\nREGRAS: não usar logotipos de marcas reais, não copiar personagens existentes, não mostrar armas ou conteúdo perigoso gratuitamente, não esconder o produto, não criar uma imagem genérica. A imagem deve parecer uma peça oficial e engraçada do universo FUTUROLOGIO.\n\nFORMATO OBRIGATÓRIO: 16:9 horizontal, 1024x576 px, composição centralizada com margem de segurança nas bordas para não cortar o produto, o nome do produto ou a assinatura. Priorizar enquadramento horizontal para a ficha do FUTUROLOGIO e compartilhamento social.`}

  async function uploadInventionImage(file){const p=currentProduct(),id=Number(window.FUTUROLOGIO_DB_ID_FOR?.(p?.id)||0),status=document.querySelector('.game-upload-status');if(!id){if(status){status.className='game-upload-status err';status.textContent='Faça login e registre esta invenção antes de enviar a imagem.'}return}if(!file||file.size>8*1024*1024){if(status){status.className='game-upload-status err';status.textContent='A imagem deve ter no máximo 8 MB.'}return}if(status){status.className='game-upload-status';status.textContent='Enviando imagem…'}try{const token=localStorage.getItem('futuro_auth_token')||'',fd=new FormData();fd.append('invention_id',String(id));fd.append('image',file,file.name||'invention-image');const r=await fetch('https://motor-invencoes.edsonfernandesvet.workers.dev/api/invention-image',{method:'POST',headers:token?{Authorization:'Bearer '+token}:{},body:fd}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Não foi possível enviar a imagem.');if(p)p.image_url='https://motor-invencoes.edsonfernandesvet.workers.dev/api/invention-image/'+id;refreshImageCard();if(status){status.className='game-upload-status ok';status.textContent='Imagem enviada e vinculada à sua invenção.'}}catch(e){if(status){status.className='game-upload-status err';status.textContent=e.message||'Falha no envio.'}}}

  function ensurePromptCard(){const result=document.getElementById('result');const panel=result?.querySelector('.panel');const stamp=panel?.querySelector('.stamp');if(!panel||!stamp||panel.querySelector('.game-prompt-card'))return;const card=document.createElement('section');card.className='game-prompt-card';card.innerHTML='<span class="game-prompt-kicker">IA // DIREÇÃO DE ARTE</span><h3>Gere a imagem do seu produto</h3><p>O FUTUROLOGIO monta automaticamente o prompt a partir da invenção. Escolha um estilo ou use o estilo oficial recomendado.</p><div class="game-style-row"><button class="game-style-btn active" data-style="toy">3D Toy-Tech</button><button class="game-style-btn" data-style="retro">Publicidade Retrô</button><button class="game-style-btn" data-style="comic">HQ Pop</button></div><textarea class="game-prompt-text" readonly aria-label="Prompt para gerar a imagem"></textarea><div class="game-prompt-actions"><button class="game-prompt-copy">COPIAR PROMPT</button></div><div class="game-image-upload"><label>Já criou a imagem em outro lugar? Envie aqui.</label><input class="game-image-file" type="file" accept="image/jpeg,image/png,image/webp,image/gif"><div class="game-upload-status">JPG, PNG ou WebP · máximo 8 MB · imagem horizontal recomendada.</div></div><div class="game-prompt-note"><b>Estilo recomendado:</b> 3D Toy-Tech Absurdo — mantém uma identidade visual consistente para todas as invenções.</div>';stamp.insertAdjacentElement('afterend',card);card.querySelectorAll('.game-style-btn').forEach(btn=>btn.onclick=()=>{selectedStyle=btn.dataset.style;card.querySelectorAll('.game-style-btn').forEach(x=>x.classList.toggle('active',x===btn));updatePrompt()});card.querySelector('.game-prompt-copy').onclick=async()=>{const text=card.querySelector('.game-prompt-text').value;try{await navigator.clipboard.writeText(text);alert('Prompt copiado.')}catch{prompt('Copie o prompt:',text)}};card.querySelector('.game-image-file').addEventListener('change',e=>uploadInventionImage(e.target.files?.[0]))}
  function updatePrompt(){ensurePromptCard();const card=document.querySelector('.game-prompt-card');if(!card)return;const p=currentProduct();if(!p)return;card.querySelector('.game-prompt-text').value=buildPrompt(p)}
  function refreshAll(){refreshImageCard();ensurePromptCard();updatePrompt()}
  const name=document.getElementById('name');if(name)new MutationObserver(refreshAll).observe(name,{childList:true,characterData:true,subtree:true});document.addEventListener('DOMContentLoaded',refreshAll);setTimeout(refreshAll,500);
})();
