(()=>{
'use strict';
if(window.__FUTUROLOGIO_GAMIFICATION_EVENTS)return;
window.__FUTUROLOGIO_GAMIFICATION_EVENTS=true;
const API='https://motor-invencoes.edsonfernandesvet.workers.dev';
const token=()=>localStorage.getItem('futuro_auth_token')||'';
let busy=false;
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function show(items){if(!items.length)return;let old=document.getElementById('futuroRewardToast');if(old)old.remove();const box=document.createElement('div');box.id='futuroRewardToast';box.innerHTML='<div class="frt-card"><div class="frt-kicker">FUTUROLOGIO™</div><div class="frt-title">PARABÉNS!</div><div class="frt-items">'+items.map(x=>'<div class="frt-item"><span>'+x.icon+'</span><div><b>'+esc(x.title)+'</b><small>'+esc(x.text)+'</small></div></div>').join('')+'</div><button type="button">CONTINUAR</button></div>';document.body.appendChild(box);requestAnimationFrame(()=>box.classList.add('is-open'));box.querySelector('button').onclick=()=>{box.classList.remove('is-open');setTimeout(()=>box.remove(),220)};setTimeout(()=>{if(document.body.contains(box)){box.classList.remove('is-open');setTimeout(()=>box.remove(),220)}},9000)}
function css(){if(document.getElementById('futuroRewardCss'))return;const s=document.createElement('style');s.id='futuroRewardCss';s.textContent='#futuroRewardToast{position:fixed;inset:0;z-index:99999;display:flex;align-items:center;justify-content:center;padding:20px;background:rgba(10,12,16,.58);backdrop-filter:blur(5px);opacity:0;transition:opacity .2s}.#futuroRewardToast{}#futuroRewardToast.is-open{opacity:1}.frt-card{width:min(440px,100%);background:#fffdf8;color:#171717;border:2px solid #171717;border-radius:24px;padding:24px;box-shadow:9px 9px 0 #171717;transform:translateY(12px) scale(.98);transition:transform .2s}.is-open .frt-card{transform:none}.frt-kicker{font-size:10px;font-weight:950;letter-spacing:.16em;color:#6f6b63}.frt-title{font-size:34px;font-weight:1000;letter-spacing:-.06em;margin:5px 0 17px}.frt-items{display:grid;gap:9px}.frt-item{display:flex;gap:12px;align-items:center;border:1.5px solid #171717;border-radius:15px;padding:12px;background:#fff}.frt-item>span{width:44px;height:44px;display:grid;place-items:center;border:1.5px solid #171717;border-radius:13px;background:#d8ff55;font-size:22px;font-weight:950;flex:0 0 44px}.frt-item b,.frt-item small{display:block}.frt-item b{font-size:14px}.frt-item small{font-size:11px;color:#6f6b63;margin-top:3px;line-height:1.35}.frt-card button{width:100%;margin-top:16px;padding:13px;border:2px solid #171717;border-radius:12px;background:#171717;color:#fff;font-weight:950;cursor:pointer}@media(max-width:500px){.frt-title{font-size:29px}.frt-card{padding:20px}}';document.head.appendChild(s)}
async function check(){if(busy||!token())return;busy=true;try{const r=await fetch(API+'/api/profile',{headers:{Authorization:'Bearer '+token(),cache:'no-store'}});if(!r.ok)return;const d=await r.json(),p=d.profile;if(!p||!p.username)return;const key='futuro_gamification_snapshot_'+String(p.username).toLowerCase();const now={level:Number(p.level||1),badges:(p.badges||[]).map(b=>String(b.code||b.id||b.name)).sort()};let prev=null;try{prev=JSON.parse(localStorage.getItem(key)||'null')}catch{}if(!prev){localStorage.setItem(key,JSON.stringify(now));return}const items=[];if(now.level>Number(prev.level||1)){items.push({icon:'↑',title:'Você passou para o nível '+now.level+'!',text:'Seu novo nível é '+String(p.role||'')+'. Continue criando para avançar ainda mais.'});if(now.level>=5&&now.level%5===0)items.push({icon:'★',title:'Medalha de nível '+now.level+' conquistada!',text:'Você atingiu um novo marco de progressão.'})}const oldBadges=new Set(prev.badges||[]);const newBadges=(p.badges||[]).filter(b=>!oldBadges.has(String(b.code||b.id||b.name)));for(const b of newBadges)items.push({icon:'★',title:b.name||'Nova medalha conquistada!',text:b.description||'Você desbloqueou uma nova conquista.'});localStorage.setItem(key,JSON.stringify(now));if(items.length)show(items)}catch{}finally{busy=false}}
css();setTimeout(check,1800);setInterval(check,5000);
})();
