(()=>{
'use strict';
if(window.__FUTURO_HOME_SOCIAL)return;window.__FUTURO_HOME_SOCIAL=true;
const API='https://motor-invencoes.edsonfernandesvet.workers.dev';
const TOKEN_KEY='futuro_auth_token';
const visitor=()=>localStorage.getItem('futuro_visitor_id')||'';
const token=()=>localStorage.getItem(TOKEN_KEY)||'';
const auth=()=>{try{return JSON.parse(localStorage.getItem('futuro_social_user')||'null')}catch{return null}};
async function api(path,opt={}){const headers={'content-type':'application/json',...(opt.headers||{})};const t=token();if(t)headers.Authorization='Bearer '+t;const r=await fetch(API+path,{...opt,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.error||'Erro no servidor'),{status:r.status,data:d});return d}
function idOf(card){const direct=Number(card?.dataset?.inventionId||card?.dataset?.recentId||0);if(direct)return direct;const href=card?.getAttribute('data-href')||card?.getAttribute('onclick')||'';const m=String(href).match(/[?&]db_invention=(\d+)/);return m?Number(m[1]):0}
function addStyles(){if(document.getElementById('homeSocialStyle'))return;const s=document.createElement('style');s.id='homeSocialStyle';s.textContent=`
.home-social{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.home-social-btn{border:1.5px solid var(--ink);background:#fff;color:var(--ink);border-radius:9px;padding:7px 9px;font:inherit;font-size:11px;font-weight:900;cursor:pointer}.home-social-btn.like.is-on{background:var(--red,#e43d30);color:#fff}.home-social-btn.comment{background:var(--lime);color:var(--ink)}.home-comment-box{display:none;margin-top:8px;gap:6px}.home-comment-box.open{display:flex}.home-comment-box input{flex:1;min-width:0;border:1.5px solid var(--ink);border-radius:9px;padding:8px;font:inherit;font-size:11px}.home-comment-box button{border:1.5px solid var(--ink);border-radius:9px;background:var(--ink);color:#fff;padding:8px 10px;font-weight:900;cursor:pointer}.home-social .views{cursor:default}.home-social .views b{font-weight:1000}
` ;document.head.appendChild(s)}
function augment(card){if(!card||card.dataset.homeSocial==='1')return;const id=idOf(card);if(!id)return;card.dataset.homeSocial='1';card.dataset.inventionId=String(id);const stats=card.querySelector('.stats');if(stats&&!stats.querySelector('.home-views')){const v=document.createElement('span');v.className='home-views';v.innerHTML='◉ '+Number(card.dataset.views||0);stats.appendChild(v)}const body=card.querySelector('.item-body');if(!body)return;const box=document.createElement('div');box.className='home-social';box.innerHTML='<button class="home-social-btn like" type="button">♡ Curtir <b class="like-count">'+Number(card.dataset.likes||0)+'</b></button><button class="home-social-btn comment" type="button">💬 Comentar <b class="comment-count">'+Number(card.dataset.comments||0)+'</b></button><span class="home-social-btn views" aria-label="Visualizações">◉ <b class="view-count">'+Number(card.dataset.views||0)+'</b></span>';const form=document.createElement('div');form.className='home-comment-box';form.innerHTML='<input maxlength="500" placeholder="Escreva um comentário…"><button type="button">Enviar</button>';body.appendChild(box);body.appendChild(form);box.querySelector('.like').onclick=e=>{e.stopPropagation();like(card)};box.querySelector('.comment').onclick=e=>{e.stopPropagation();form.classList.toggle('open');if(form.classList.contains('open'))form.querySelector('input').focus()};form.querySelector('button').onclick=e=>{e.stopPropagation();comment(card,form)};form.querySelector('input').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();comment(card,form)}};refresh(card)}
async function refresh(card){const id=idOf(card);if(!id)return;try{const d=await api('/api/inventions/'+id);const like=card.querySelector('.like-count'),comment=card.querySelector('.comment-count'),views=card.querySelector('.view-count'),oldView=card.querySelector('.home-views');if(like)like.textContent=Number(d.likes||0);if(comment)comment.textContent=Number((d.comments||[]).length);if(views)views.textContent=Number(d.views||0);if(oldView)oldView.innerHTML='◉ '+Number(d.views||0);card.dataset.likes=Number(d.likes||0);card.dataset.comments=Number((d.comments||[]).length);card.dataset.views=Number(d.views||0)}catch{}}
async function like(card){if(!auth()||!token()){window.openAuth?.('login');if(!window.openAuth)location.href='./criar.html';return}const id=idOf(card);if(!id)return;const b=card.querySelector('.like');b.disabled=true;try{const d=await api('/api/inventions/'+id+'/like',{method:'POST',body:'{}'});b.classList.toggle('is-on',!!d.liked);b.firstChild.textContent=d.liked?'♥ Curtir ':'♡ Curtir ';await refresh(card)}catch(e){if(e.status===401)window.openAuth?.('login');else alert(e.message)}finally{b.disabled=false}}
async function comment(card,form){if(!auth()||!token()){window.openAuth?.('login');if(!window.openAuth)location.href='./criar.html';return}const input=form.querySelector('input'),text=input.value.trim();if(!text)return;const id=idOf(card);if(!id)return;const btn=form.querySelector('button');btn.disabled=true;try{await api('/api/inventions/'+id+'/comment',{method:'POST',body:JSON.stringify({text})});input.value='';form.classList.remove('open');await refresh(card)}catch(e){if(e.status===401)window.openAuth?.('login');else alert(e.message)}finally{btn.disabled=false}}
async function registerView(card){const id=idOf(card);if(!id)return;try{const d=await api('/api/inventions/'+id+'/view',{method:'POST',body:JSON.stringify({visitor_id:visitor()})});if(d.views!=null){card.dataset.views=d.views;const c=card.querySelector('.view-count'),s=card.querySelector('.home-views');if(c)c.textContent=d.views;if(s)s.innerHTML='◉ '+d.views}}catch{}}
function scan(){addStyles();document.querySelectorAll('.feed .item').forEach(augment)}
document.addEventListener('click',e=>{const card=e.target.closest('.feed .item');if(!card||e.target.closest('.home-social,.home-comment-box,button'))return;registerView(card);},true);
new MutationObserver(scan).observe(document.body,{childList:true,subtree:true});scan();
})();
