(()=>{
'use strict';
if(window.__FUTUROLOGIO_SHARE_FIX)return;
window.__FUTUROLOGIO_SHARE_FIX=true;
const API='https://motor-invencoes.edsonfernandesvet.workers.dev';
const token=()=>localStorage.getItem('futuro_auth_token')||'';
function product(){return window.FUTUROLOGIO_CURRENT_PRODUCT||null}
function dbId(){const q=new URLSearchParams(location.search).get('db_invention');if(q&&/^\d+$/.test(q))return Number(q);const p=product();try{return Number(p?.__dbId||window.FUTUROLOGIO_CURRENT_DB_ID||window.FUTUROLOGIO_DB_ID_FOR?.(p?.id)||0)}catch{return Number(p?.__dbId||0)}}
function shareUrl(){const id=dbId();return id?API+'/share/'+id:location.href}
function css(){if(document.getElementById('shareFixCss'))return;const s=document.createElement('style');s.id='shareFixCss';s.textContent='.share-fix{margin-top:15px}.share-fix-summary{display:inline-flex;align-items:center;justify-content:center;gap:7px;background:#d8ff55;color:#171717;border:2px solid #171717;border-radius:12px;padding:13px 17px;font-weight:950;cursor:pointer;list-style:none}.share-fix-summary::-webkit-details-marker{display:none}.share-fix-grid{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.share-fix-grid a,.share-fix-grid button{border:1.5px solid #171717;border-radius:10px;padding:10px 13px;min-width:105px;font:900 12px/1 system-ui,sans-serif;cursor:pointer;text-decoration:none;text-align:center;color:#fff}.sf-wa{background:#25d366}.sf-tg{background:#229ed9}.sf-fb{background:#1877f2}.sf-x{background:#111}.sf-th{background:#333}.sf-ig{background:#d13b73}.sf-native{background:#4c668d}.sf-copy{background:#fff;color:#171717!important}.share-fix-note{display:block;margin-top:8px;font-size:11px;color:#6f6b63}.share-fix[open] .share-fix-summary{border-bottom-left-radius:8px;border-bottom-right-radius:8px}@media(max-width:600px){.share-fix-grid a,.share-fix-grid button{flex:1 1 calc(50% - 8px);min-width:0}}';document.head.appendChild(s)}
function productData(){const p=product()||{};const name=p.name||document.getElementById('name')?.textContent?.trim()||'Invenção FUTUROLOGIO™';const raw=p.what||p.concept||document.getElementById('what')?.textContent||'';const desc=String(raw).replace(/\s+/g,' ').trim();return {name,desc:desc.length>180?desc.slice(0,177)+'...':desc}}
function logShare(){const id=dbId();if(!id||!token())return;try{fetch(API+'/api/inventions/'+id+'/share',{method:'POST',headers:{Authorization:'Bearer '+token(),'content-type':'application/json'},body:'{}',keepalive:true})}catch{}}
function make(){css();const result=document.getElementById('result');if(!result||result.classList.contains('hidden'))return;let box=document.getElementById('shareFix');if(!box){const old=document.getElementById('shareBtn');box=document.createElement('details');box.id='shareFix';box.className='share-fix';box.innerHTML='<summary class="share-fix-summary">↗ COMPARTILHAR INVENÇÃO</summary><div class="share-fix-grid"><a class="sf-wa" target="_blank" rel="noopener">WhatsApp</a><a class="sf-tg" target="_blank" rel="noopener">Telegram</a><a class="sf-fb" target="_blank" rel="noopener">Facebook</a><a class="sf-x" target="_blank" rel="noopener">X</a><a class="sf-th" target="_blank" rel="noopener">Threads</a><a class="sf-ig" target="_blank" rel="noopener">Instagram</a><button type="button" class="sf-native">Compartilhar no celular</button><button type="button" class="sf-copy">Copiar link</button></div><span class="share-fix-note">A prévia inclui a foto, a descrição da invenção e um convite para criar.</span>';if(old)old.replaceWith(box);else{const anchor=result.querySelector('.stamp')||result.lastElementChild;anchor?.insertAdjacentElement('beforebegin',box)}bind(box)}const u=shareUrl(),d=productData(),title=d.name+' — FUTUROLOGIO™',cta='Crie seu produto absurdo você também!';const text=[title,d.desc,cta].filter(Boolean).join('\n\n');box.querySelector('.sf-wa').href='https://wa.me/?text='+encodeURIComponent(text+'\n'+u);box.querySelector('.sf-tg').href='https://t.me/share/url?url='+encodeURIComponent(u)+'&text='+encodeURIComponent(text);box.querySelector('.sf-fb').href='https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(u);box.querySelector('.sf-x').href='https://twitter.com/intent/tweet?text='+encodeURIComponent(text)+'&url='+encodeURIComponent(u);box.querySelector('.sf-th').href='https://www.threads.net/intent/post?text='+encodeURIComponent(text+' '+u);box.querySelector('.sf-ig').href='https://www.instagram.com/';box.querySelector('.sf-native').onclick=async()=>{if(navigator.share){try{await navigator.share({title,text,url:u});logShare()}catch(e){if(e?.name!=='AbortError')copy(u)}}else copy(u)};box.querySelector('.sf-copy').onclick=()=>{copy(u);logShare()}}
async function copy(u){try{await navigator.clipboard.writeText(u);alert('Link da invenção copiado.')}catch{prompt('Copie o link da invenção:',u)}}
function tick(){make()}setTimeout(tick,500);setTimeout(tick,1200);setInterval(tick,1500)
})();
