(() => {
  'use strict';
  const API='https://motor-invencoes.edsonfernandesvet.workers.dev';
  const TOKEN_KEY='futuro_auth_token', USER_KEY='futuro_social_user', MAP_KEY='futuro_db_invention_ids';
  const state={user:null,currentId:null,currentProduct:null,liked:false,shareXp:0};
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const loadUser=()=>{try{return JSON.parse(localStorage.getItem(USER_KEY)||'null')}catch{return null}};
  const saveUser=u=>localStorage.setItem(USER_KEY,JSON.stringify(u));
  const dbMap=()=>{try{return JSON.parse(localStorage.getItem(MAP_KEY)||'{}')}catch{return {}}};
  const initials=n=>(String(n||'C').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'C');
  const token=()=>localStorage.getItem(TOKEN_KEY)||'';
  async function api(path,opt={}){const h={...(opt.headers||{}),'content-type':'application/json'};if(token())h.Authorization='Bearer '+token();const r=await fetch(API+path,{...opt,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.error||'Erro no servidor'),{data:d,status:r.status});return d}

  function mount(){
    if(document.getElementById('ftSocialBar'))return;
    const style=document.createElement('style');style.textContent=`
      .ft-social-bar{max-width:1080px;margin:0 auto;padding:10px 20px;border-bottom:1.5px solid var(--ink);display:flex;align-items:center;justify-content:space-between;gap:10px;background:#fffdf8}.ft-account{display:flex;align-items:center;gap:9px;min-width:0}.ft-avatar,.ft-big-avatar{border:1.5px solid var(--ink);border-radius:50%;display:grid;place-items:center;background:var(--lime);font-weight:950}.ft-avatar{width:34px;height:34px}.ft-big-avatar{width:58px;height:58px;font-size:22px}.ft-user b{display:block;font-size:12px}.ft-user span{font-size:10px;color:var(--muted)}.ft-actions,.ft-social-row{display:flex;gap:7px;flex-wrap:wrap}.ft-btn{border:1.5px solid var(--ink);background:#fff;border-radius:10px;padding:8px 10px;font-weight:850;font-size:12px;cursor:pointer}.ft-btn.dark{background:var(--ink);color:#fff}.ft-btn.lime{background:var(--lime)}.ft-profile{max-width:1080px;margin:15px auto 0;padding:0 20px;display:none}.ft-profile.open{display:block}.ft-profile-card{background:var(--paper);border:2px solid var(--ink);border-radius:18px;padding:16px;box-shadow:4px 4px 0 var(--ink);display:grid;grid-template-columns:auto 1fr auto;gap:14px;align-items:center}.ft-stats{display:flex;gap:8px;flex-wrap:wrap;margin-top:7px}.ft-stat{border:1px solid var(--ink);border-radius:9px;padding:6px 9px;background:#fff;font-size:10px}.ft-stat b{display:block;font-size:15px}.ft-social{margin-top:16px;border-top:1.5px solid var(--line);padding-top:14px}.ft-social h3{margin:0 0 9px;font-size:14px}.ft-like.on{background:var(--red);color:#fff}.ft-comments{margin-top:13px}.ft-comment-row{display:flex;gap:7px}.ft-comment-row input{flex:1;min-width:0;border:1.5px solid var(--ink);border-radius:10px;padding:9px;font:inherit;font-size:12px}.ft-comment{font-size:11px;border-left:3px solid var(--ink);padding:6px 9px;margin-top:7px;background:#fff}.ft-xp{font-size:10px;font-weight:900;background:var(--lime);border:1px solid var(--ink);padding:2px 5px;border-radius:99px}.ft-badges{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.ft-badge{font-size:10px;border:1px solid var(--ink);border-radius:99px;padding:4px 7px;background:#fff}@media(max-width:760px){.ft-social-bar{padding:10px 12px}.ft-profile{padding:0 12px}.ft-profile-card{grid-template-columns:auto 1fr}.ft-profile-card>.ft-actions{grid-column:1/-1}}
    `;document.head.appendChild(style);
    const header=document.querySelector('header');if(!header)return;
    const bar=document.createElement('div');bar.className='ft-social-bar';bar.id='ftSocialBar';bar.innerHTML=`<div class="ft-account"><div class="ft-avatar" id="ftAvatar">C</div><div class="ft-user"><b id="ftUser">Visitante</b><span id="ftRole">Entre para salvar seu progresso</span></div></div><div class="ft-actions"><button class="ft-btn" id="ftProfileBtn">Meu perfil</button><button class="ft-btn dark" id="ftLoginBtn">Entrar / cadastrar</button></div>`;header.appendChild(bar);
    const prof=document.createElement('section');prof.className='ft-profile';prof.id='ftProfile';prof.innerHTML=`<div class="ft-profile-card"><div class="ft-big-avatar" id="ftBigAvatar">C</div><div><h3 id="ftProfileName" style="margin:0 0 4px">Visitante</h3><div class="ft-stats"><div class="ft-stat"><b id="ftXp">0</b>XP</div><div class="ft-stat"><b id="ftLevel">1</b>nível</div><div class="ft-stat"><b id="ftCreations">0</b>criações</div></div><div class="ft-badges" id="ftBadges"><span class="ft-badge">Sem medalha ainda</span></div></div><div class="ft-actions"><button class="ft-btn" id="ftCloseProfile">Fechar</button></div></div>`;header.insertAdjacentElement('afterend',prof);
    document.getElementById('ftProfileBtn').onclick=()=>prof.classList.toggle('open');document.getElementById('ftCloseProfile').onclick=()=>prof.classList.remove('open');
    document.getElementById('ftLoginBtn').onclick=()=>{if(loadUser()){localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(USER_KEY);location.reload()}else if(window.openAuth)window.openAuth('register');else alert('Use o botão CRIAR MEU PRODUTO para entrar ou cadastrar-se.')};
    state.user=loadUser();renderUser();observeResult();
  }

  function renderUser(){const u=state.user;const a=initials(u?.username);document.getElementById('ftAvatar').textContent=a;document.getElementById('ftBigAvatar').textContent=a;document.getElementById('ftUser').textContent=u?.username||'Visitante';document.getElementById('ftRole').textContent=u?`${u.role||'Curioso Iniciante'} · ${u.xp||0} XP`:'Entre para salvar seu progresso';document.getElementById('ftProfileName').textContent=u?.username||'Visitante';document.getElementById('ftXp').textContent=u?.xp||0;document.getElementById('ftLevel').textContent=u?.level||1;document.getElementById('ftCreations').textContent=u?.creations||0;document.getElementById('ftLoginBtn').textContent=u?'Sair':'Entrar / cadastrar';}

  function findCurrentProduct(){
    try{const shared=new URLSearchParams(location.search).get('invention');const list=window.FUTUROLOGIO_PRODUCTS||window.PRODUCTS||[];if(shared){const p=list.find(x=>String(x.id)===String(shared));if(p)return p}}catch{}
    try{const raw=JSON.parse(localStorage.getItem('futuro_used_v3')||'null');const id=Array.isArray(raw)?raw[raw.length-1]:raw?.id;const list=window.FUTUROLOGIO_PRODUCTS||window.PRODUCTS||[];if(id){const p=list.find(x=>String(x.id)===String(id));if(p)return p}}catch{}
    const name=document.getElementById('name')?.textContent?.trim();const list=window.FUTUROLOGIO_PRODUCTS||window.PRODUCTS||[];return name?list.find(x=>String(x.name).trim()===name)||null:null;
  }
  function resolveDbId(){const p=state.currentProduct||findCurrentProduct();state.currentProduct=p;if(!p)return 0;const direct=window.FUTUROLOGIO_DB_ID_FOR?.(p.id)||Number(dbMap()[p.id]||0);state.currentId=Number(direct)||0;return state.currentId}
  async function waitForDbId(){for(let i=0;i<20;i++){const id=resolveDbId();if(id)return id;await new Promise(r=>setTimeout(r,100))}return 0}

  function observeResult(){const result=document.getElementById('result');if(!result)return;const obs=new MutationObserver(()=>{if(!result.classList.contains('hidden'))setTimeout(attachSocial,20)});obs.observe(result,{attributes:true,attributeFilter:['class'],childList:true,subtree:true});if(!result.classList.contains('hidden'))attachSocial();}
  function attachSocial(){const result=document.getElementById('result');if(!result||result.querySelector('.ft-social'))return;const stamp=result.querySelector('.stamp');if(!stamp)return;resolveDbId();const box=document.createElement('div');box.className='ft-social';box.innerHTML=`<h3>Interação social</h3><div class="ft-social-row"><button class="ft-btn ft-like" id="ftLike">♡ Curtir <span class="ft-xp">XP</span></button><button class="ft-btn" data-platform="whatsapp">WhatsApp</button><button class="ft-btn" data-platform="facebook">Facebook</button><button class="ft-btn" data-platform="x">X</button><button class="ft-btn" data-platform="instagram">Instagram</button><button class="ft-btn" data-platform="threads">Threads</button><button class="ft-btn" data-platform="copy">Copiar link</button><button class="ft-btn" data-platform="native">Compartilhar</button></div><div class="ft-comments"><div class="ft-comment-row"><input id="ftCommentInput" maxlength="500" placeholder="Comente nesta invenção…"><button class="ft-btn lime" id="ftCommentBtn">Comentar</button></div><div id="ftCommentList"></div></div>`;stamp.parentNode.insertBefore(box,stamp);box.querySelector('#ftLike').onclick=socialLike;box.querySelector('#ftCommentBtn').onclick=socialComment;box.querySelectorAll('[data-platform]').forEach(b=>b.onclick=()=>socialShare(b.dataset.platform));}
  function requireUser(){if(state.user)return true;if(window.openAuth){window.openAuth('register');return false}alert('Entre ou cadastre-se para interagir.');return false}
  async function socialLike(){if(!requireUser())return;const id=await waitForDbId();if(!id)return alert('Esta invenção ainda não foi registrada no servidor.');try{const d=await api(`/api/inventions/${id}/like`,{method:'POST',body:'{}'});state.liked=d.liked??!state.liked;const b=document.getElementById('ftLike');b.classList.toggle('on',state.liked);b.firstChild.textContent=state.liked?'♥ Descurtir ':'♡ Curtir ';if(d.user){state.user=d.user;saveUser(d.user);renderUser()}}catch(e){alert(e.message||'Não foi possível registrar a curtida.');}}
  async function socialComment(){if(!requireUser())return;const id=resolveDbId(),input=document.getElementById('ftCommentInput'),text=input?.value.trim();if(!id)return alert('Esta invenção ainda não foi registrada no servidor.');if(!text)return;try{const d=await api(`/api/inventions/${id}/comment`,{method:'POST',body:JSON.stringify({text})});const list=document.getElementById('ftCommentList');const c=d.comment||{text};const div=document.createElement('div');div.className='ft-comment';div.innerHTML=`<b>${esc(state.user.username)}</b>: ${esc(c.text)}`;list.prepend(div);input.value='';if(d.user){state.user=d.user;saveUser(d.user);renderUser()}}catch(e){alert(e.message||'Não foi possível publicar o comentário.');}}
  async function socialShare(platform){if(!requireUser())return;const id=await waitForDbId();if(!id)return alert('Esta invenção ainda não foi registrada no servidor.');const name=document.getElementById('name')?.textContent||'Invenção FUTUROLOGIO™',url=location.origin+location.pathname+'?invention='+encodeURIComponent(state.currentProduct?.id||''),text=name+' — uma invenção que não existe. FUTUROLOGIO™';let target='';if(platform==='whatsapp')target='https://wa.me/?text='+encodeURIComponent(text+' '+url);else if(platform==='facebook')target='https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(url);else if(platform==='x')target='https://twitter.com/intent/tweet?text='+encodeURIComponent(text)+'&url='+encodeURIComponent(url);else if(platform==='instagram'){try{await navigator.clipboard.writeText(text+' '+url);alert('Texto e link copiados. Cole no Instagram.')}catch{prompt('Copie o texto e link:',text+' '+url)}target='https://www.instagram.com/';}else if(platform==='threads')target='https://www.threads.net/intent/post?text='+encodeURIComponent(text+' '+url);else if(platform==='copy'){try{await navigator.clipboard.writeText(url);alert('Link copiado.')}catch{prompt('Copie o link:',url)}target='';}else if(platform==='native'&&navigator.share){try{await navigator.share({title:name,text,url})}catch{return}}else target=url;if(target)window.open(target,'_blank','noopener,noreferrer');try{const d=await api(`/api/inventions/${id}/share`,{method:'POST',body:JSON.stringify({platform})});if(d.user){state.user=d.user;saveUser(d.user);renderUser()}}catch(e){if(e.status!==401)alert(e.message||'O compartilhamento foi aberto, mas não foi registrado no servidor.');}}

  const t=setInterval(()=>{if(document.querySelector('header')){clearInterval(t);mount()}},50);
})();
