-- FUTUROLOGIO™ D1 schema
-- Keeps legacy invention columns required by the existing motor.

CREATE TABLE IF NOT EXISTS USERS (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  email TEXT UNIQUE,
  google_id TEXT UNIQUE,
  password_hash TEXT,
  avatar TEXT,
  xp INTEGER NOT NULL DEFAULT 0,
  level INTEGER NOT NULL DEFAULT 1,
  plan TEXT NOT NULL DEFAULT 'free',
  daily_creations INTEGER NOT NULL DEFAULT 0,
  daily_creation_date TEXT,
  extra_credits INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AVATAR_PROFILES (
  user_id TEXT PRIMARY KEY,
  sex TEXT NOT NULL CHECK (sex IN ('masculino','feminino')),
  config TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS INVENTIONS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  concept TEXT NOT NULL,
  fingerprint TEXT NOT NULL UNIQUE,
  data TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USER_INVENTIONS (
  user_id TEXT NOT NULL,
  invention_id INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, invention_id),
  FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
  FOREIGN KEY (invention_id) REFERENCES INVENTIONS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS INVENTION_OWNERS (
  invention_id INTEGER PRIMARY KEY,
  user_id TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (invention_id) REFERENCES INVENTIONS(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMMENTS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  invention_id INTEGER NOT NULL,
  text TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
  FOREIGN KEY (invention_id) REFERENCES INVENTIONS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LIKES (
  user_id TEXT NOT NULL,
  invention_id INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, invention_id),
  FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
  FOREIGN KEY (invention_id) REFERENCES INVENTIONS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SHARES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  invention_id INTEGER NOT NULL,
  platform TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
  FOREIGN KEY (invention_id) REFERENCES INVENTIONS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS XP_EVENTS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  reference_type TEXT,
  reference_id TEXT,
  xp INTEGER NOT NULL,
  event_date TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BADGES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  requirement TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_BADGES (
  user_id TEXT NOT NULL,
  badge_id INTEGER NOT NULL,
  earned_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, badge_id),
  FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
  FOREIGN KEY (badge_id) REFERENCES BADGES(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SUBSCRIPTIONS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  plan TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  provider TEXT,
  provider_reference TEXT,
  started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TEXT,
  FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CREDIT_PURCHASES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  credits INTEGER NOT NULL,
  provider TEXT,
  provider_reference TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_inventions_user ON USER_INVENTIONS(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invention_owners_user ON INVENTION_OWNERS(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_invention ON COMMENTS(invention_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_shares_user_date ON SHARES(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_xp_events_user_date ON XP_EVENTS(user_id, event_date);
CREATE INDEX IF NOT EXISTS idx_inventions_category ON INVENTIONS(category);
