INSERT OR IGNORE INTO BADGES(code,name,description,requirement) VALUES
('FIRST_CREATION','Primeira Invenção','Criou sua primeira invenção no FUTUROLOGIO.','1 criação'),
('TEN_CREATIONS','Dez Invenções','Chegou a dez invenções criadas.','10 criações'),
('FIFTY_CREATIONS','Cinquenta Invenções','Chegou a cinquenta invenções criadas.','50 criações'),
('FIRST_PHOTO_UPLOAD','Primeira Foto','Enviou a primeira imagem de uma invenção.','1 foto enviada'),
('FIVE_PHOTO_UPLOADS','Colecionador Visual','Enviou cinco imagens.','5 fotos enviadas'),
('TEN_PHOTO_UPLOADS','Estúdio Criativo','Enviou dez imagens.','10 fotos enviadas'),
('TWENTY_FIVE_PHOTO_UPLOADS','Diretor de Arte','Enviou vinte e cinco imagens.','25 fotos enviadas'),
('FIFTY_PHOTO_UPLOADS','Mestre Visual','Enviou cinquenta imagens.','50 fotos enviadas'),
('HUNDRED_PHOTO_UPLOADS','Lenda do Catálogo','Enviou cem imagens.','100 fotos enviadas'),
('TWO_HUNDRED_FIFTY_PHOTO_UPLOADS','Galeria do Futuro','Enviou duzentas e cinquenta imagens.','250 fotos enviadas'),
('FIRST_LIKE','Primeira Curtida','Curtiu uma invenção pela primeira vez.','1 curtida'),
('HUNDRED_LIKES_RECEIVED','Cem Curtidas','Recebeu cem curtidas em suas invenções.','100 curtidas recebidas'),
('FIRST_COMMENT','Primeiro Comentário','Comentou em uma invenção pela primeira vez.','1 comentário'),
('FIFTY_COMMENTS','Cinquenta Comentários','Fez cinquenta comentários.','50 comentários'),
('FIRST_SHARE','Primeiro Compartilhamento','Compartilhou uma invenção pela primeira vez.','1 compartilhamento'),
('FIFTY_SHARES','Cinquenta Compartilhamentos','Compartilhou cinquenta vezes.','50 compartilhamentos'),
('CATEGORY_EXPLORER','Explorador de Categorias','Criou invenções em dez categorias diferentes.','10 categorias'),
('MULTICATEGORY_CREATOR','Criador Multicategoria','Criou invenções em vinte categorias diferentes.','20 categorias'),
('BIZARRO_EXPLORER','Explorador do Bizarro','Criou uma invenção na categoria Bizarro ou Nojento.','1 criação na categoria Bizarro ou Nojento');
