ALTER TABLE INVENTIONS ADD COLUMN image_key TEXT;
ALTER TABLE INVENTIONS ADD COLUMN image_content_type TEXT;
ALTER TABLE INVENTIONS ADD COLUMN image_source TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_inventions_image_key ON INVENTIONS(image_key) WHERE image_key IS NOT NULL;
