CREATE TABLE IF NOT EXISTS SITE_VISITS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  visitor_id TEXT NOT NULL,
  page TEXT NOT NULL DEFAULT '/',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_site_visits_visitor ON SITE_VISITS(visitor_id);
CREATE INDEX IF NOT EXISTS idx_site_visits_created ON SITE_VISITS(created_at DESC);
