-- FUTUROLOGIO™ profile settings
ALTER TABLE USERS ADD COLUMN sex TEXT;
ALTER TABLE USERS ADD COLUMN age INTEGER;
ALTER TABLE USERS ADD COLUMN address TEXT;
ALTER TABLE USERS ADD COLUMN bio TEXT;
ALTER TABLE USERS ADD COLUMN profile_photo_key TEXT;
ALTER TABLE USERS ADD COLUMN profile_photo_content_type TEXT;
