-- FUTUROLOGIO™: missões diárias de créditos
ALTER TABLE DAILY_CREDIT_MISSIONS ADD COLUMN photo_rewarded INTEGER NOT NULL DEFAULT 0;
ALTER TABLE DAILY_CREDIT_MISSIONS ADD COLUMN ad_clicks INTEGER NOT NULL DEFAULT 0;
ALTER TABLE DAILY_CREDIT_MISSIONS ADD COLUMN ad_rewarded INTEGER NOT NULL DEFAULT 0;
ALTER TABLE DAILY_CREDIT_MISSIONS ADD COLUMN share_actions INTEGER NOT NULL DEFAULT 0;
ALTER TABLE DAILY_CREDIT_MISSIONS ADD COLUMN photo_actions INTEGER NOT NULL DEFAULT 0;
