-- FUTUROLOGIO™: contadores diários para ações de compartilhamento e foto
ALTER TABLE DAILY_CREDIT_MISSIONS ADD COLUMN share_actions INTEGER NOT NULL DEFAULT 0;
ALTER TABLE DAILY_CREDIT_MISSIONS ADD COLUMN photo_actions INTEGER NOT NULL DEFAULT 0;
